//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pe.ElectroPeru.SGI.Aplicacion.Core.Message {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MensajesSistemaResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MensajesSistemaResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pe.ElectroPeru.SGI.Aplicacion.Core.Message.MensajesSistemaResource", typeof(MensajesSistemaResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione un Archivo por favor..
        /// </summary>
        public static string ArchivoObligatorio {
            get {
                return ResourceManager.GetString("ArchivoObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La asociación ya existe..
        /// </summary>
        public static string ColaboradorProyectoRepetido {
            get {
                return ResourceManager.GetString("ColaboradorProyectoRepetido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede copiar los estadios de un mismo registro.
        /// </summary>
        public static string CopiarEstadioIgual {
            get {
                return ResourceManager.GetString("CopiarEstadioIgual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El registro no existe.
        /// </summary>
        public static string CopiarEstadioNoExiste {
            get {
                return ResourceManager.GetString("CopiarEstadioNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elija otro registro, este no contiene estadios.
        /// </summary>
        public static string CopiarEstadioNoTiene {
            get {
                return ResourceManager.GetString("CopiarEstadioNoTiene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El departamento ya existe..
        /// </summary>
        public static string DepartamentoRepetido {
            get {
                return ResourceManager.GetString("DepartamentoRepetido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error inesperado. Inténtelo nuevamente..
        /// </summary>
        public static string EtiquetaError {
            get {
                return ResourceManager.GetString("EtiquetaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede eliminar este Objetivo, ya que cuenta con Indicador(es) asociado(s).
        /// </summary>
        public static string EtiquetaMsgValidacionConsistencia {
            get {
                return ResourceManager.GetString("EtiquetaMsgValidacionConsistencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede eliminar esta Acción, ya que cuenta con Objetivo(s) Estratégico(s) FONAFE asociado(s).
        /// </summary>
        public static string EtiquetaMsgValidacionConsistenciaAES {
            get {
                return ResourceManager.GetString("EtiquetaMsgValidacionConsistenciaAES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede eliminar este Objetivo, ya que cuenta con Objetivo(s) Específico(s) Empresa(s) asociado(s).
        /// </summary>
        public static string EtiquetaMsgValidacionConsistenciaOEE {
            get {
                return ResourceManager.GetString("EtiquetaMsgValidacionConsistenciaOEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede eliminar este Objetivo, ya que cuenta con Objetivo(s) Estratégico(s) Empresa(s) asociado(s).
        /// </summary>
        public static string EtiquetaMsgValidacionConsistenciaOEF {
            get {
                return ResourceManager.GetString("EtiquetaMsgValidacionConsistenciaOEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede eliminar este Objetivo, ya que cuenta con Acción(es) Estratégica(s) Sectorial (es) asociado(s).
        /// </summary>
        public static string EtiquetaMsgValidacionConsistenciaOES {
            get {
                return ResourceManager.GetString("EtiquetaMsgValidacionConsistenciaOES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede eliminar esta Perspectiva, ya que cuenta con Objetivo(s) Estratégico(s) FONAFE asociado(s).
        /// </summary>
        public static string EtiquetaMsgValidacionConsistenciaPerspectiva {
            get {
                return ResourceManager.GetString("EtiquetaMsgValidacionConsistenciaPerspectiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hay campos que son obligatorios y no se ha llenado información..
        /// </summary>
        public static string EtiquetaValidarCamposObligatorios {
            get {
                return ResourceManager.GetString("EtiquetaValidarCamposObligatorios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los firmantes ya están completos o el orden de firmante ya existe..
        /// </summary>
        public static string FirmanteNoValido {
            get {
                return ResourceManager.GetString("FirmanteNoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe un estadio con la misma Descripción..
        /// </summary>
        public static string FlujoAprobacionEstadioDescripcionExiste {
            get {
                return ResourceManager.GetString("FlujoAprobacionEstadioDescripcionExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe un estadio con los mismos datos de Orden de Prioridad y Descripción.
        /// </summary>
        public static string FlujoAprobacionEstadioExiste {
            get {
                return ResourceManager.GetString("FlujoAprobacionEstadioExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe un estadio con el mismo orden de prioridad.
        /// </summary>
        public static string FlujoAprobacionEstadioOrdenExiste {
            get {
                return ResourceManager.GetString("FlujoAprobacionEstadioOrdenExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe un flujo de aprobación con los mismos datos..
        /// </summary>
        public static string FlujoAprobacionExiste {
            get {
                return ResourceManager.GetString("FlujoAprobacionExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha configurado un Flujo de Aprobación para la Forma de Edición {0}..
        /// </summary>
        public static string FlujoAprobacionFormaEdicionNoExiste {
            get {
                return ResourceManager.GetString("FlujoAprobacionFormaEdicionNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe un Flujo de Aprobación con la Unidad Operativa, Tipo de Servicio, Tipo de Requerimiento ingresado..
        /// </summary>
        public static string FlujoAprobacionNoExiste {
            get {
                return ResourceManager.GetString("FlujoAprobacionNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe un Flujo de Aprobación con la Unidad Operativa, Tipo de Servicio, Tipo de Requerimiento y Forma de Edición ingresado..
        /// </summary>
        public static string FlujoAprobacionNoExisteReporte {
            get {
                return ResourceManager.GetString("FlujoAprobacionNoExisteReporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe establecer un Orden mayor a 1..
        /// </summary>
        public static string FlujoAprobacionOrdenIgualUno {
            get {
                return ResourceManager.GetString("FlujoAprobacionOrdenIgualUno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El contratista ya se registro.
        /// </summary>
        public static string MsjContratistaExiste {
            get {
                return ResourceManager.GetString("MsjContratistaExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Persona Investigador ya se encuentra registrada..
        /// </summary>
        public static string PersonaInvestigadorExiste {
            get {
                return ResourceManager.GetString("PersonaInvestigadorExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Persona ya se encuentra registrada..
        /// </summary>
        public static string PersonaInvolucradaExiste {
            get {
                return ResourceManager.GetString("PersonaInvolucradaExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Persona Supervisor ya se encuentra registrada..
        /// </summary>
        public static string PersonaSupervisorExiste {
            get {
                return ResourceManager.GetString("PersonaSupervisorExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Persona Testigo ya se encuentra registrada..
        /// </summary>
        public static string PersonaTestigoExiste {
            get {
                return ResourceManager.GetString("PersonaTestigoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puede registrar una combinación ya existente..
        /// </summary>
        public static string PlantillaExiste {
            get {
                return ResourceManager.GetString("PlantillaExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puede registrar una Fecha de Inicio de Vigencia menor a la que ya existe..
        /// </summary>
        public static string PlantillaFechaInicioVigenciaMenor {
            get {
                return ResourceManager.GetString("PlantillaFechaInicioVigenciaMenor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El formato de la Fecha de Inicio de Vigencia es incorrecto..
        /// </summary>
        public static string PlantillaFechaInicioVigenciIncorrecto {
            get {
                return ResourceManager.GetString("PlantillaFechaInicioVigenciIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe una Plantilla ni un Flujo de Aprobación para la combinación ingresada..
        /// </summary>
        public static string PlantillaFlujoAprobacionNoExiste {
            get {
                return ResourceManager.GetString("PlantillaFlujoAprobacionNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede eliminar, existen contratos asociados a esta plantilla..
        /// </summary>
        public static string PlantillaNoEliminar {
            get {
                return ResourceManager.GetString("PlantillaNoEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe una Plantilla con el Tipo de Servicio, Tipo de Requerimiento, Tipo de Documento y Tipo Adhesión ingresado..
        /// </summary>
        public static string PlantillaNoExiste {
            get {
                return ResourceManager.GetString("PlantillaNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede modificar, existen contratos asociados a esta plantilla..
        /// </summary>
        public static string PlantillaNoModificar {
            get {
                return ResourceManager.GetString("PlantillaNoModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe un Párrafo con el mismo Orden y Título para la Plantilla..
        /// </summary>
        public static string PlantillaParrafoExiste {
            get {
                return ResourceManager.GetString("PlantillaParrafoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe un Párrafo para la Plantilla seleccionada..
        /// </summary>
        public static string PlantillaParrafoNoExiste {
            get {
                return ResourceManager.GetString("PlantillaParrafoNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Orden del Párrafo ya se encuentra registrada para esta Plantilla..
        /// </summary>
        public static string PlantillaParrafoOrdenExiste {
            get {
                return ResourceManager.GetString("PlantillaParrafoOrdenExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Título del Párrafo ya se encuentra registrada para esta Plantilla..
        /// </summary>
        public static string PlantillaParrafoTituloExiste {
            get {
                return ResourceManager.GetString("PlantillaParrafoTituloExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unidad Operativa Y  Fecha planificada, no pueden tener datos iguales..
        /// </summary>
        public static string ProcesoAuditoriaExiste {
            get {
                return ResourceManager.GetString("ProcesoAuditoriaExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Proyecto ya existe..
        /// </summary>
        public static string ProyectoRepetido {
            get {
                return ResourceManager.GetString("ProyectoRepetido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe un Proyecto con el mismo código. Ingrese otro código..
        /// </summary>
        public static string ProyectoRepetidoIntegridad {
            get {
                return ResourceManager.GetString("ProyectoRepetidoIntegridad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puede Reabrir la Acción porque su estado no lo permite..
        /// </summary>
        public static string RecordSeguimientoAccionAbierto {
            get {
                return ResourceManager.GetString("RecordSeguimientoAccionAbierto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puede registrar más seguimientos porque el estado de la acción lo permite..
        /// </summary>
        public static string RecordSeguimientoAccionCerrado {
            get {
                return ResourceManager.GetString("RecordSeguimientoAccionCerrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La acción seleccionada no le corresponde como Responsable..
        /// </summary>
        public static string ResponsableNoCorresponde {
            get {
                return ResourceManager.GetString("ResponsableNoCorresponde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Empresa Matriz es obligatoria..
        /// </summary>
        public static string UnidadOperativaMatrizObligatorio {
            get {
                return ResourceManager.GetString("UnidadOperativaMatrizObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe una Unidad Operativa con el mismo Código de Identificación ..
        /// </summary>
        public static string UOCIExiste {
            get {
                return ResourceManager.GetString("UOCIExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Ya existe una Unidad Operativa con el mismo Nombre.&quot;.
        /// </summary>
        public static string UONombreExiste {
            get {
                return ResourceManager.GetString("UONombreExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El proyecto está siendo utilizado por el Módulo Actúa Positivo..
        /// </summary>
        public static string ViolacionIntegridadActuaPositivo {
            get {
                return ResourceManager.GetString("ViolacionIntegridadActuaPositivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El proyecto está siendo utilizado por el Módulo Capacitación..
        /// </summary>
        public static string ViolacionIntegridadAsignacionProyecto {
            get {
                return ResourceManager.GetString("ViolacionIntegridadAsignacionProyecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario actual fue deshabilitado del sistema..
        /// </summary>
        public static string ViolacionIntegridadColaborador {
            get {
                return ResourceManager.GetString("ViolacionIntegridadColaborador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El colaborador está siendo utilizado por el Módulo Actúa Positivo..
        /// </summary>
        public static string ViolacionIntegridadColaboradorActuaPositivo {
            get {
                return ResourceManager.GetString("ViolacionIntegridadColaboradorActuaPositivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede eliminar el &quot;Colaborador&quot; ya que está siendo usado/referenciado en una &quot;Asignación&quot;..
        /// </summary>
        public static string ViolacionIntegridadColaboradorAsignacionProyectoPersona {
            get {
                return ResourceManager.GetString("ViolacionIntegridadColaboradorAsignacionProyectoPersona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede eliminar el &quot;Colaborador&quot; ya que está siendo usado/referenciado en una &quot;Investigación&quot;..
        /// </summary>
        public static string ViolacionIntegridadColaboradorInestigacionInvestigador {
            get {
                return ResourceManager.GetString("ViolacionIntegridadColaboradorInestigacionInvestigador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede eliminar el &quot;Colaborador&quot; ya que está siendo usado/referenciado en &quot;Testigo&quot;..
        /// </summary>
        public static string ViolacionIntegridadColaboradorInvestigacionTestigo {
            get {
                return ResourceManager.GetString("ViolacionIntegridadColaboradorInvestigacionTestigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede eliminar el &quot;Departamento&quot; ya que está siendo usado/referenciado en un &quot;Área&quot;.
        /// </summary>
        public static string ViolacionIntegridadDepartamento {
            get {
                return ResourceManager.GetString("ViolacionIntegridadDepartamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede eliminar la &quot;Empresa&quot; ya que está siendo usado/referenciado en un &quot;Proyecto&quot;..
        /// </summary>
        public static string ViolacionIntegridadEmpresa {
            get {
                return ResourceManager.GetString("ViolacionIntegridadEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Empresa ya se encuentra reportada..
        /// </summary>
        public static string ViolacionIntegridadEmpresaReportada {
            get {
                return ResourceManager.GetString("ViolacionIntegridadEmpresaReportada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede eliminar el &quot;Área&quot; ya que está siendo usado/referenciado en un &quot;Grupo&quot;..
        /// </summary>
        public static string ViolacionIntegridadGrupo {
            get {
                return ResourceManager.GetString("ViolacionIntegridadGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Observador seleccionado, ya se encuentra ingresado..
        /// </summary>
        public static string ViolacionIntegridadObservadorInterno {
            get {
                return ResourceManager.GetString("ViolacionIntegridadObservadorInterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El proyecto no existe..
        /// </summary>
        public static string ViolacionIntegridadProyecto {
            get {
                return ResourceManager.GetString("ViolacionIntegridadProyecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El proyecto está asociado a un colaborador..
        /// </summary>
        public static string ViolacionIntegridadProyectoColaboradorProyecto {
            get {
                return ResourceManager.GetString("ViolacionIntegridadProyectoColaboradorProyecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede eliminar el &quot;Proyecto&quot; ya que está siendo usado/referenciado en un &quot;Departamento&quot;..
        /// </summary>
        public static string ViolacionIntegridadProyectoDelete {
            get {
                return ResourceManager.GetString("ViolacionIntegridadProyectoDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El proyecto está siendo utilizado por el Módulo Gestión de Lesiones..
        /// </summary>
        public static string ViolacionIntegridadProyectoExpedienteMedico {
            get {
                return ResourceManager.GetString("ViolacionIntegridadProyectoExpedienteMedico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El proyecto está siendo utilizado por el Módulo HHT..
        /// </summary>
        public static string ViolacionIntegridadProyectoHHT {
            get {
                return ResourceManager.GetString("ViolacionIntegridadProyectoHHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El proyecto está siendo utilizado por el Módulo Gestión de Incidentes / Otros..
        /// </summary>
        public static string ViolacionIntegridadProyectoInvestigacioRecords {
            get {
                return ResourceManager.GetString("ViolacionIntegridadProyectoInvestigacioRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El proyecto está siendo utilizado por el Módulo Visita Gerencial..
        /// </summary>
        public static string ViolacionIntegridadProyectoVisitaGerencialConfNotif {
            get {
                return ResourceManager.GetString("ViolacionIntegridadProyectoVisitaGerencialConfNotif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Reportante ya se encuentra ingresado..
        /// </summary>
        public static string ViolacionIntegridadReportante {
            get {
                return ResourceManager.GetString("ViolacionIntegridadReportante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El SubContratista seleccionado, ya se encuentra ingresado..
        /// </summary>
        public static string ViolacionIntegridadSubContratista {
            get {
                return ResourceManager.GetString("ViolacionIntegridadSubContratista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe un registro para este Año y Periodicidad. Elimine el registro y vuelva a intentarlo..
        /// </summary>
        public static string ViolacionRegistro {
            get {
                return ResourceManager.GetString("ViolacionRegistro", resourceCulture);
            }
        }
    }
}
