//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pe.ElectroPeru.SGI.Presentacion.Recursos.Politicas {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ParametroResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ParametroResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pe.ElectroPeru.SGI.Presentacion.Recursos.Politicas.ParametroResource", typeof(ParametroResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código.
        /// </summary>
        public static string EtiquetaCodigoIdentificador {
            get {
                return ResourceManager.GetString("EtiquetaCodigoIdentificador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string EtiquetaDescripcionParametro {
            get {
                return ResourceManager.GetString("EtiquetaDescripcionParametro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formulario Parámetro.
        /// </summary>
        public static string EtiquetaDlgFormularioParametrosGenerales {
            get {
                return ResourceManager.GetString("EtiquetaDlgFormularioParametrosGenerales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Esta seguro de eliminar los parámetros seleccionados?.
        /// </summary>
        public static string EtiquetaDlgMsgEliminar {
            get {
                return ResourceManager.GetString("EtiquetaDlgMsgEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de querer eliminar los registros realizados?.
        /// </summary>
        public static string EtiquetaMessageDlgEstaSeguro {
            get {
                return ResourceManager.GetString("EtiquetaMessageDlgEstaSeguro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Esta seguro de querer grabar los cambios realizados?.
        /// </summary>
        public static string EtiquetaMessageDlgEstaSeguroGrabar {
            get {
                return ResourceManager.GetString("EtiquetaMessageDlgEstaSeguroGrabar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string EtiquetaNombreParametro {
            get {
                return ResourceManager.GetString("EtiquetaNombreParametro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parámetro.
        /// </summary>
        public static string EtiquetaParametro {
            get {
                return ResourceManager.GetString("EtiquetaParametro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parámetro de Empresa.
        /// </summary>
        public static string EtiquetaParametroEmpresa {
            get {
                return ResourceManager.GetString("EtiquetaParametroEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        public static string EtiquetaParametroEmpresaNo {
            get {
                return ResourceManager.GetString("EtiquetaParametroEmpresaNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si.
        /// </summary>
        public static string EtiquetaParametroEmpresaSi {
            get {
                return ResourceManager.GetString("EtiquetaParametroEmpresaSi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todos.
        /// </summary>
        public static string EtiquetaParametroEmpresaTodos {
            get {
                return ResourceManager.GetString("EtiquetaParametroEmpresaTodos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permite Agregar.
        /// </summary>
        public static string EtiquetaPermiteAgregar {
            get {
                return ResourceManager.GetString("EtiquetaPermiteAgregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permite Eliminar.
        /// </summary>
        public static string EtiquetaPermiteEliminar {
            get {
                return ResourceManager.GetString("EtiquetaPermiteEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permite Modificar.
        /// </summary>
        public static string EtiquetaPermiteModificar {
            get {
                return ResourceManager.GetString("EtiquetaPermiteModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resultados de la Busqueda.
        /// </summary>
        public static string EtiquetaResultadosBusqueda {
            get {
                return ResourceManager.GetString("EtiquetaResultadosBusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Secciones.
        /// </summary>
        public static string EtiquetaSecciones {
            get {
                return ResourceManager.GetString("EtiquetaSecciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sistema.
        /// </summary>
        public static string EtiquetaSistema {
            get {
                return ResourceManager.GetString("EtiquetaSistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Parámetro.
        /// </summary>
        public static string EtiquetaTipoParametro {
            get {
                return ResourceManager.GetString("EtiquetaTipoParametro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar Parámetros Generales.
        /// </summary>
        public static string EtiquetaTituloDlgBuscarParametrosGenerales {
            get {
                return ResourceManager.GetString("EtiquetaTituloDlgBuscarParametrosGenerales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar.
        /// </summary>
        public static string EtiquetaTituloDlgConfirmar {
            get {
                return ResourceManager.GetString("EtiquetaTituloDlgConfirmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar Parámetro.
        /// </summary>
        public static string EtiquetaTituloEliminar {
            get {
                return ResourceManager.GetString("EtiquetaTituloEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parámetros Generales.
        /// </summary>
        public static string EtiquetaTituloPrincipal {
            get {
                return ResourceManager.GetString("EtiquetaTituloPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código.
        /// </summary>
        public static string GridCodigo {
            get {
                return ResourceManager.GetString("GridCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nivel.
        /// </summary>
        public static string GridNivel {
            get {
                return ResourceManager.GetString("GridNivel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string GridNombre {
            get {
                return ResourceManager.GetString("GridNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar.
        /// </summary>
        public static string GridSeleccionar {
            get {
                return ResourceManager.GetString("GridSeleccionar", resourceCulture);
            }
        }
    }
}
