//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pe.ElectroPeru.SGI.Presentacion.Recursos.Base {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PrincipalResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PrincipalResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pe.ElectroPeru.SGI.Presentacion.Recursos.Base.PrincipalResource", typeof(PrincipalResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido(a) @usuario al Sistema de Gestión de Indicadores, el cual le permitirá ingresar variables y sus valores, para así obtener los indicadores requeridos. Mediante las configuraciones se ofrece mayor flexibilidad en las funcionalidades. El sistema le mantendrá informado mediante notificaciones automáticas y la generación de reportes..
        /// </summary>
        public static string DescripcionSistema {
            get {
                return ResourceManager.GetString("DescripcionSistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuración.
        /// </summary>
        public static string EtiquetaConfiguracion {
            get {
                return ResourceManager.GetString("EtiquetaConfiguracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión.
        /// </summary>
        public static string EtiquetaGestion {
            get {
                return ResourceManager.GetString("EtiquetaGestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ElectroPerú.
        /// </summary>
        public static string EtiquetaNombreEmpresa {
            get {
                return ResourceManager.GetString("EtiquetaNombreEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notificaciones Automáticas.
        /// </summary>
        public static string EtiquetaNotificacionesAutomaticas {
            get {
                return ResourceManager.GetString("EtiquetaNotificacionesAutomaticas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reportes.
        /// </summary>
        public static string EtiquetaReportes {
            get {
                return ResourceManager.GetString("EtiquetaReportes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguimiento.
        /// </summary>
        public static string EtiquetaSeguimiento {
            get {
                return ResourceManager.GetString("EtiquetaSeguimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CARACTERÍSTICAS PRINCIPALES.
        /// </summary>
        public static string EtiquetaSuptitulo {
            get {
                return ResourceManager.GetString("EtiquetaSuptitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido al Sistema de Gestión de Indicadores.
        /// </summary>
        public static string EtiquetaTitulo {
            get {
                return ResourceManager.GetString("EtiquetaTitulo", resourceCulture);
            }
        }
    }
}
