//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pe.ElectroPeru.SGI.Presentacion.Recursos.Seguridad.Usuarios {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UsuariosResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UsuariosResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pe.ElectroPeru.SGI.Presentacion.Recursos.Seguridad.Usuarios.UsuariosResource", typeof(UsuariosResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido.
        /// </summary>
        public static string EtiquetaApellido {
            get {
                return ResourceManager.GetString("EtiquetaApellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDITAR.
        /// </summary>
        public static string EtiquetaBotonEditar {
            get {
                return ResourceManager.GetString("EtiquetaBotonEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ELIMINAR.
        /// </summary>
        public static string EtiquetaBotonEliminar {
            get {
                return ResourceManager.GetString("EtiquetaBotonEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRABAR.
        /// </summary>
        public static string EtiquetaBotonGuardar {
            get {
                return ResourceManager.GetString("EtiquetaBotonGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrar Usuarios.
        /// </summary>
        public static string EtiquetaBotonRegistrar {
            get {
                return ResourceManager.GetString("EtiquetaBotonRegistrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar Contraseña.
        /// </summary>
        public static string EtiquetaCambiarContrasena {
            get {
                return ResourceManager.GetString("EtiquetaCambiarContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargo.
        /// </summary>
        public static string EtiquetaCargo {
            get {
                return ResourceManager.GetString("EtiquetaCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña Anterior.
        /// </summary>
        public static string EtiquetaContrasenaAntigua {
            get {
                return ResourceManager.GetString("EtiquetaContrasenaAntigua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña Nueva.
        /// </summary>
        public static string EtiquetaContrasenaNueva {
            get {
                return ResourceManager.GetString("EtiquetaContrasenaNueva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        public static string EtiquetaContrasenia {
            get {
                return ResourceManager.GetString("EtiquetaContrasenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo.
        /// </summary>
        public static string EtiquetaEMail {
            get {
                return ResourceManager.GetString("EtiquetaEMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FechaActividad.
        /// </summary>
        public static string EtiquetaFechaActividad {
            get {
                return ResourceManager.GetString("EtiquetaFechaActividad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información de Usuario.
        /// </summary>
        public static string EtiquetaInformacion {
            get {
                return ResourceManager.GetString("EtiquetaInformacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listado de Usuarios.
        /// </summary>
        public static string EtiquetaLista {
            get {
                return ResourceManager.GetString("EtiquetaLista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desea eliminar el usuario?.
        /// </summary>
        public static string EtiquetaMensajeEliminar {
            get {
                return ResourceManager.GetString("EtiquetaMensajeEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puede eliminar el registro porque tiene asociados.
        /// </summary>
        public static string EtiquetaMensajeErrorAsociados {
            get {
                return ResourceManager.GetString("EtiquetaMensajeErrorAsociados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string EtiquetaNombre {
            get {
                return ResourceManager.GetString("EtiquetaNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número Documento.
        /// </summary>
        public static string EtiquetaNumeroDocumento {
            get {
                return ResourceManager.GetString("EtiquetaNumeroDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reestablecer Contraseña.
        /// </summary>
        public static string EtiquetaReestablecerContrasena {
            get {
                return ResourceManager.GetString("EtiquetaReestablecerContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Documento.
        /// </summary>
        public static string EtiquetaTipoDocumento {
            get {
                return ResourceManager.GetString("EtiquetaTipoDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USUARIOS.
        /// </summary>
        public static string EtiquetaTituloFormulario {
            get {
                return ResourceManager.GetString("EtiquetaTituloFormulario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MANTENIMIENTO DE USUARIOS.
        /// </summary>
        public static string EtiquetaTituloPrincipal {
            get {
                return ResourceManager.GetString("EtiquetaTituloPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        public static string EtiquetaUsuario {
            get {
                return ResourceManager.GetString("EtiquetaUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario y/o Contraseña Incorrecta.
        /// </summary>
        public static string EtiquetaUsuarioIncorrecto {
            get {
                return ResourceManager.GetString("EtiquetaUsuarioIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string GridEstado {
            get {
                return ResourceManager.GetString("GridEstado", resourceCulture);
            }
        }
    }
}
