//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pe.ElectroPeru.SGI.Presentacion.Recursos.Mantenimiento.Indicador {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IndicadorResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IndicadorResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pe.ElectroPeru.SGI.Presentacion.Recursos.Mantenimiento.Indicador.IndicadorResourc" +
                            "e", typeof(IndicadorResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Indicador.
        /// </summary>
        public static string BotonAgregarIndicador {
            get {
                return ResourceManager.GetString("BotonAgregarIndicador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AGREGAR FÓRMULA.
        /// </summary>
        public static string EtiquetaAgregarFormula {
            get {
                return ResourceManager.GetString("EtiquetaAgregarFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ámbito.
        /// </summary>
        public static string EtiquetaAmbito {
            get {
                return ResourceManager.GetString("EtiquetaAmbito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Año.
        /// </summary>
        public static string EtiquetaAnual {
            get {
                return ResourceManager.GetString("EtiquetaAnual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Área.
        /// </summary>
        public static string EtiquetaArea {
            get {
                return ResourceManager.GetString("EtiquetaArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ELIMINAR.
        /// </summary>
        public static string EtiquetaBotonEliminar {
            get {
                return ResourceManager.GetString("EtiquetaBotonEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GRABAR.
        /// </summary>
        public static string EtiquetaBotonGuardar {
            get {
                return ResourceManager.GetString("EtiquetaBotonGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción Indicador.
        /// </summary>
        public static string EtiquetaDescripcion {
            get {
                return ResourceManager.GetString("EtiquetaDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Día.
        /// </summary>
        public static string EtiquetaDiario {
            get {
                return ResourceManager.GetString("EtiquetaDiario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EDITAR FÓRMULA.
        /// </summary>
        public static string EtiquetaEditarFormula {
            get {
                return ResourceManager.GetString("EtiquetaEditarFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Especificar.
        /// </summary>
        public static string EtiquetaEspecificar {
            get {
                return ResourceManager.GetString("EtiquetaEspecificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Evaluación.
        /// </summary>
        public static string EtiquetaEvaluacion {
            get {
                return ResourceManager.GetString("EtiquetaEvaluacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fórmula.
        /// </summary>
        public static string EtiquetaFormula {
            get {
                return ResourceManager.GetString("EtiquetaFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingreso de Fórmula.
        /// </summary>
        public static string EtiquetaFormulaIngreso {
            get {
                return ResourceManager.GetString("EtiquetaFormulaIngreso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generales.
        /// </summary>
        public static string EtiquetaGenerales {
            get {
                return ResourceManager.GetString("EtiquetaGenerales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Indicador.
        /// </summary>
        public static string EtiquetaIndicador {
            get {
                return ResourceManager.GetString("EtiquetaIndicador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista.
        /// </summary>
        public static string EtiquetaLista {
            get {
                return ResourceManager.GetString("EtiquetaLista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea eliminar el Indicador?.
        /// </summary>
        public static string EtiquetaMensajeEliminar {
            get {
                return ResourceManager.GetString("EtiquetaMensajeEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mes.
        /// </summary>
        public static string EtiquetaMes {
            get {
                return ResourceManager.GetString("EtiquetaMes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Meta Anual.
        /// </summary>
        public static string EtiquetaMetaAnual {
            get {
                return ResourceManager.GetString("EtiquetaMetaAnual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Meta.
        /// </summary>
        public static string EtiquetaMetas {
            get {
                return ResourceManager.GetString("EtiquetaMetas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Periodicidad.
        /// </summary>
        public static string EtiquetaPeriodicidad {
            get {
                return ResourceManager.GetString("EtiquetaPeriodicidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ponderación.
        /// </summary>
        public static string EtiquetaPonderacion {
            get {
                return ResourceManager.GetString("EtiquetaPonderacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ratio Máximo.
        /// </summary>
        public static string EtiquetaRatioMaximo {
            get {
                return ResourceManager.GetString("EtiquetaRatioMaximo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ratio Mínimo.
        /// </summary>
        public static string EtiquetaRatioMinimo {
            get {
                return ResourceManager.GetString("EtiquetaRatioMinimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Responsable.
        /// </summary>
        public static string EtiquetaResponsable {
            get {
                return ResourceManager.GetString("EtiquetaResponsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Semana.
        /// </summary>
        public static string EtiquetaSemana {
            get {
                return ResourceManager.GetString("EtiquetaSemana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Semestre.
        /// </summary>
        public static string EtiquetaSemestre {
            get {
                return ResourceManager.GetString("EtiquetaSemestre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expresión de Fórmula.
        /// </summary>
        public static string EtiquetaTabFormula {
            get {
                return ResourceManager.GetString("EtiquetaTabFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generales.
        /// </summary>
        public static string EtiquetaTabGenerales {
            get {
                return ResourceManager.GetString("EtiquetaTabGenerales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo.
        /// </summary>
        public static string EtiquetaTipo {
            get {
                return ResourceManager.GetString("EtiquetaTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BANDEJA DE INDICADOR.
        /// </summary>
        public static string EtiquetaTituloBandeja {
            get {
                return ResourceManager.GetString("EtiquetaTituloBandeja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INGRESO DE INDICADOR.
        /// </summary>
        public static string EtiquetaTituloIndicador {
            get {
                return ResourceManager.GetString("EtiquetaTituloIndicador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información General.
        /// </summary>
        public static string EtiquetaTituloInformacionGeneral {
            get {
                return ResourceManager.GetString("EtiquetaTituloInformacionGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Trimestre.
        /// </summary>
        public static string EtiquetaTrimestre {
            get {
                return ResourceManager.GetString("EtiquetaTrimestre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unidad de Medida.
        /// </summary>
        public static string EtiquetaUnidadMedida {
            get {
                return ResourceManager.GetString("EtiquetaUnidadMedida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valores.
        /// </summary>
        public static string EtiquetaValor {
            get {
                return ResourceManager.GetString("EtiquetaValor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Meta Estimada.
        /// </summary>
        public static string EtiquetaValorMeta {
            get {
                return ResourceManager.GetString("EtiquetaValorMeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor Real.
        /// </summary>
        public static string EtiquetaValorReal {
            get {
                return ResourceManager.GetString("EtiquetaValorReal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vigente Desde.
        /// </summary>
        public static string EtiquetaVigenteDesde {
            get {
                return ResourceManager.GetString("EtiquetaVigenteDesde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vigente Hasta.
        /// </summary>
        public static string EtiquetaVigenteHasta {
            get {
                return ResourceManager.GetString("EtiquetaVigenteHasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ámbito.
        /// </summary>
        public static string GridAmbito {
            get {
                return ResourceManager.GetString("GridAmbito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Año.
        /// </summary>
        public static string GridAnio {
            get {
                return ResourceManager.GetString("GridAnio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Área.
        /// </summary>
        public static string GridArea {
            get {
                return ResourceManager.GetString("GridArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción Indicador.
        /// </summary>
        public static string GridDescripcion {
            get {
                return ResourceManager.GetString("GridDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        public static string GridEstado {
            get {
                return ResourceManager.GetString("GridEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor Evaluación.
        /// </summary>
        public static string GridEvaluacion {
            get {
                return ResourceManager.GetString("GridEvaluacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fórmula.
        /// </summary>
        public static string GridFormula {
            get {
                return ResourceManager.GetString("GridFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Indicador.
        /// </summary>
        public static string GridIndicador {
            get {
                return ResourceManager.GetString("GridIndicador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string GridNombre {
            get {
                return ResourceManager.GetString("GridNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Variables.
        /// </summary>
        public static string GridNombreVariable {
            get {
                return ResourceManager.GetString("GridNombreVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Responsable.
        /// </summary>
        public static string GridResponsable {
            get {
                return ResourceManager.GetString("GridResponsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle de Periodicidad.
        /// </summary>
        public static string GridSubTipoPeriodicidad {
            get {
                return ResourceManager.GetString("GridSubTipoPeriodicidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo.
        /// </summary>
        public static string GridTipo {
            get {
                return ResourceManager.GetString("GridTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Meta.
        /// </summary>
        public static string GridValorMeta {
            get {
                return ResourceManager.GetString("GridValorMeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor Real.
        /// </summary>
        public static string GridValorReal {
            get {
                return ResourceManager.GetString("GridValorReal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vigente Desde.
        /// </summary>
        public static string GridVigenteDesde {
            get {
                return ResourceManager.GetString("GridVigenteDesde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vigente Hasta.
        /// </summary>
        public static string GridVigenteHasta {
            get {
                return ResourceManager.GetString("GridVigenteHasta", resourceCulture);
            }
        }
    }
}
