//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pe.ElectroPeru.SGI.Presentacion.Recursos.Proceso.PlanOperativo {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PlanOperativoResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlanOperativoResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pe.ElectroPeru.SGI.Presentacion.Recursos.Proceso.PlanOperativo.PlanOperativoResou" +
                            "rce", typeof(PlanOperativoResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NOMBRE INDICADOR.
        /// </summary>
        public static string EtiquetaNombreIndicador {
            get {
                return ResourceManager.GetString("EtiquetaNombreIndicador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OBJETIVO ESTRATEGICO EMPRESA.
        /// </summary>
        public static string EtiquetaObjetivoEstrategicoEmpresa {
            get {
                return ResourceManager.GetString("EtiquetaObjetivoEstrategicoEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OBJETIVO ESTRATEGICO COORPORATIVO.
        /// </summary>
        public static string EtiquetaObjetivoEstrategicoFONAFE {
            get {
                return ResourceManager.GetString("EtiquetaObjetivoEstrategicoFONAFE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BANDEJA DE PLAN OPERATIVO.
        /// </summary>
        public static string EtiquetaTituloBandeja {
            get {
                return ResourceManager.GetString("EtiquetaTituloBandeja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OBJETIVOS ESTRATÉGICOS EMPRESA (Asociados).
        /// </summary>
        public static string EtiquetaTituloOEE {
            get {
                return ResourceManager.GetString("EtiquetaTituloOEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OBJETIVOS ESTRATÉGICOS CORPORATIVOS (Asociados).
        /// </summary>
        public static string EtiquetaTituloOEF {
            get {
                return ResourceManager.GetString("EtiquetaTituloOEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 2017.
        /// </summary>
        public static string Grid2017 {
            get {
                return ResourceManager.GetString("Grid2017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 2018.
        /// </summary>
        public static string Grid2018 {
            get {
                return ResourceManager.GetString("Grid2018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 2019.
        /// </summary>
        public static string Grid2019 {
            get {
                return ResourceManager.GetString("Grid2019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 2020.
        /// </summary>
        public static string Grid2020 {
            get {
                return ResourceManager.GetString("Grid2020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 2021.
        /// </summary>
        public static string Grid2021 {
            get {
                return ResourceManager.GetString("Grid2021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 2022.
        /// </summary>
        public static string Grid2022 {
            get {
                return ResourceManager.GetString("Grid2022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acción Estratégica Institucional.
        /// </summary>
        public static string GridAEI {
            get {
                return ResourceManager.GetString("GridAEI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forma de Cálculo.
        /// </summary>
        public static string GridFormaCalculo {
            get {
                return ResourceManager.GetString("GridFormaCalculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre del Indicador.
        /// </summary>
        public static string GridNombreIndicador {
            get {
                return ResourceManager.GetString("GridNombreIndicador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre Objetivo Estrategico Fonafe.
        /// </summary>
        public static string GridNombreObjetivoEstrategicoFonafe {
            get {
                return ResourceManager.GetString("GridNombreObjetivoEstrategicoFonafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Objetivo Estratégico Empresa.
        /// </summary>
        public static string GridObjetivoEstrategicoEmpresa {
            get {
                return ResourceManager.GetString("GridObjetivoEstrategicoEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Objetivo Estratégico Corporativo.
        /// </summary>
        public static string GridObjetivoEstrategicoFONAFE {
            get {
                return ResourceManager.GetString("GridObjetivoEstrategicoFONAFE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unidad de Medida.
        /// </summary>
        public static string GridUM {
            get {
                return ResourceManager.GetString("GridUM", resourceCulture);
            }
        }
    }
}
