//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pe.ElectroPeru.SGI.Presentacion.Recursos.Mantenimiento.ObjetivoEstrategicoEmpresa {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OEEResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OEEResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pe.ElectroPeru.SGI.Presentacion.Recursos.Mantenimiento.ObjetivoEstrategicoEmpresa" +
                            ".OEEResource", typeof(OEEResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar O.E.E..
        /// </summary>
        public static string BotonAgregarOEE {
            get {
                return ResourceManager.GetString("BotonAgregarOEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acción Estratégica Institucional.
        /// </summary>
        public static string EtiquetaAccionEstrategicaInstitucional {
            get {
                return ResourceManager.GetString("EtiquetaAccionEstrategicaInstitucional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Área.
        /// </summary>
        public static string EtiquetaArea {
            get {
                return ResourceManager.GetString("EtiquetaArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ELIMINAR.
        /// </summary>
        public static string EtiquetaBotonEliminar {
            get {
                return ResourceManager.GetString("EtiquetaBotonEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GRABAR.
        /// </summary>
        public static string EtiquetaBotonGuardar {
            get {
                return ResourceManager.GetString("EtiquetaBotonGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción Objetivo Estratégico de Empresa.
        /// </summary>
        public static string EtiquetaDescripcion {
            get {
                return ResourceManager.GetString("EtiquetaDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción Objetivo Estratégico Empresa.
        /// </summary>
        public static string EtiquetaDescripcionObjetivoEstrategicoEmpresa {
            get {
                return ResourceManager.GetString("EtiquetaDescripcionObjetivoEstrategicoEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Indicador.
        /// </summary>
        public static string EtiquetaIndicador {
            get {
                return ResourceManager.GetString("EtiquetaIndicador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista.
        /// </summary>
        public static string EtiquetaLista {
            get {
                return ResourceManager.GetString("EtiquetaLista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea eliminar el Objetivo Estratégico de Empresa?.
        /// </summary>
        public static string EtiquetaMensajeEliminar {
            get {
                return ResourceManager.GetString("EtiquetaMensajeEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modelo Conceptual.
        /// </summary>
        public static string EtiquetaModeloConceptual {
            get {
                return ResourceManager.GetString("EtiquetaModeloConceptual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre Objetivo Estratégico de Empresa.
        /// </summary>
        public static string EtiquetaNombre {
            get {
                return ResourceManager.GetString("EtiquetaNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre Objetivo Estratégico Empresa.
        /// </summary>
        public static string EtiquetaNombreObjetivoEstrategicoEmpresa {
            get {
                return ResourceManager.GetString("EtiquetaNombreObjetivoEstrategicoEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Objetivo Estratégico Empresa.
        /// </summary>
        public static string EtiquetaObjetivoEstrategicoEmpresa {
            get {
                return ResourceManager.GetString("EtiquetaObjetivoEstrategicoEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Responsable.
        /// </summary>
        public static string EtiquetaResponsable {
            get {
                return ResourceManager.GetString("EtiquetaResponsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generales.
        /// </summary>
        public static string EtiquetaTabGenerales {
            get {
                return ResourceManager.GetString("EtiquetaTabGenerales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acción(es) Estratégica(s) Institucional(es) Asociada(s).
        /// </summary>
        public static string EtiquetaTabObjetivoEstrategicoEmpresaAccionEstrategicaInstitucional {
            get {
                return ResourceManager.GetString("EtiquetaTabObjetivoEstrategicoEmpresaAccionEstrategicaInstitucional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Indicadores Asociados.
        /// </summary>
        public static string EtiquetaTabObjetivoEstrategicoEmpresaDetalle {
            get {
                return ResourceManager.GetString("EtiquetaTabObjetivoEstrategicoEmpresaDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo.
        /// </summary>
        public static string EtiquetaTipo {
            get {
                return ResourceManager.GetString("EtiquetaTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BANDEJA DE OBJETIVO ESTRATÉGICO EMPRESA.
        /// </summary>
        public static string EtiquetaTituloBandeja {
            get {
                return ResourceManager.GetString("EtiquetaTituloBandeja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información General.
        /// </summary>
        public static string EtiquetaTituloInformacionGeneral {
            get {
                return ResourceManager.GetString("EtiquetaTituloInformacionGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INGRESO DE OBJETIVO ESTRATÉGICO EMPRESA.
        /// </summary>
        public static string EtiquetaTituloObjetivoEstrategicoEmpresa {
            get {
                return ResourceManager.GetString("EtiquetaTituloObjetivoEstrategicoEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acción Estratégica Institucional.
        /// </summary>
        public static string GridAccionEstrategicaInstitucional {
            get {
                return ResourceManager.GetString("GridAccionEstrategicaInstitucional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción Objetivo Estratégico Empresa.
        /// </summary>
        public static string GridDescripcionObjetivoEstrategicoEmpresa {
            get {
                return ResourceManager.GetString("GridDescripcionObjetivoEstrategicoEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        public static string GridEstado {
            get {
                return ResourceManager.GetString("GridEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Indicador.
        /// </summary>
        public static string GridIndicador {
            get {
                return ResourceManager.GetString("GridIndicador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modelo Conceptual.
        /// </summary>
        public static string GridModeloConceptual {
            get {
                return ResourceManager.GetString("GridModeloConceptual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre Objetivo Estratégico Empresa.
        /// </summary>
        public static string GridNombreObjetivoEstrategicoEmpresa {
            get {
                return ResourceManager.GetString("GridNombreObjetivoEstrategicoEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Objetivo Estratégico Empresa.
        /// </summary>
        public static string GridObjetivoEstrategicoEmpresa {
            get {
                return ResourceManager.GetString("GridObjetivoEstrategicoEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Responsable.
        /// </summary>
        public static string GridResponsable {
            get {
                return ResourceManager.GetString("GridResponsable", resourceCulture);
            }
        }
    }
}
