//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pe.ElectroPeru.SGI.Presentacion.Recursos.Mensajes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MensajeResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MensajeResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pe.ElectroPeru.SGI.Presentacion.Recursos.Mensajes.MensajeResource", typeof(MensajeResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentario Válido.
        /// </summary>
        public static string ComentarioValido {
            get {
                return ResourceManager.GetString("ComentarioValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desea anular este registro?.
        /// </summary>
        public static string ConfirmacionAnular {
            get {
                return ResourceManager.GetString("ConfirmacionAnular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro de aprobar las modificaciones realizadas?.
        /// </summary>
        public static string ConfirmacionAprobar {
            get {
                return ResourceManager.GetString("ConfirmacionAprobar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro de autorizar la solicitud de modificación?.
        /// </summary>
        public static string ConfirmacionAutorizar {
            get {
                return ResourceManager.GetString("ConfirmacionAutorizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro de denegar la solicitud de modificación?.
        /// </summary>
        public static string ConfirmacionDenegar {
            get {
                return ResourceManager.GetString("ConfirmacionDenegar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro de eliminar el registro?.
        /// </summary>
        public static string ConfirmacionEliminacion {
            get {
                return ResourceManager.GetString("ConfirmacionEliminacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desea guardar este registro?.
        /// </summary>
        public static string ConfirmacionGuardar {
            get {
                return ResourceManager.GetString("ConfirmacionGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desea modificar el contenido del contrato?.
        /// </summary>
        public static string ConfirmacionModificarContrato {
            get {
                return ResourceManager.GetString("ConfirmacionModificarContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro de rechazar la solicitud de modificación?.
        /// </summary>
        public static string ConfirmacionRechazar {
            get {
                return ResourceManager.GetString("ConfirmacionRechazar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar una fecha..
        /// </summary>
        public static string DebeSeleccionarFecha {
            get {
                return ResourceManager.GetString("DebeSeleccionarFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar un registro..
        /// </summary>
        public static string DebeSeleccionarRegistro {
            get {
                return ResourceManager.GetString("DebeSeleccionarRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar sólo un registro..
        /// </summary>
        public static string DebeSeleccionarUnRegistro {
            get {
                return ResourceManager.GetString("DebeSeleccionarUnRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se produjo un error al grabar el registro..
        /// </summary>
        public static string ErrorAlGrabar {
            get {
                return ResourceManager.GetString("ErrorAlGrabar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View model no definido..
        /// </summary>
        public static string ErrorCargarViewModel {
            get {
                return ResourceManager.GetString("ErrorCargarViewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El correo no se pudo enviar.
        /// </summary>
        public static string EtiquetaErrorEnvioReporte {
            get {
                return ResourceManager.GetString("EtiquetaErrorEnvioReporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error inesperado. Inténtelo nuevamente.
        /// </summary>
        public static string EtiquetaErrorRegistro {
            get {
                return ResourceManager.GetString("EtiquetaErrorRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato de Archivo no soportado..
        /// </summary>
        public static string EtiquetaFormatoArchivoNoSoportado {
            get {
                return ResourceManager.GetString("EtiquetaFormatoArchivoNoSoportado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desea eliminar el Registro?.
        /// </summary>
        public static string EtiquetaMensajeEliminarRegistro {
            get {
                return ResourceManager.GetString("EtiquetaMensajeEliminarRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tiene permisos suficientes para realizar esta operación.
        /// </summary>
        public static string EtiquetaMensajePermisoDenegado {
            get {
                return ResourceManager.GetString("EtiquetaMensajePermisoDenegado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desea reactivar el Registro?.
        /// </summary>
        public static string EtiquetaMensajeReactivarRegistro {
            get {
                return ResourceManager.GetString("EtiquetaMensajeReactivarRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ejecuto ningun proceso..
        /// </summary>
        public static string EtiquetaNoEjecutoNingunProceso {
            get {
                return ResourceManager.GetString("EtiquetaNoEjecutoNingunProceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El correo se envió con éxito.
        /// </summary>
        public static string EtiquetaSeEnvioReporte {
            get {
                return ResourceManager.GetString("EtiquetaSeEnvioReporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tamaño del archivo no debe superar los {0} MB..
        /// </summary>
        public static string EtiquetaTamanioArchivoAnexoMaximo {
            get {
                return ResourceManager.GetString("EtiquetaTamanioArchivoAnexoMaximo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tamaño de la foto no debe superar los {0} MB..
        /// </summary>
        public static string EtiquetaTamanioArchivoFotoMaximo {
            get {
                return ResourceManager.GetString("EtiquetaTamanioArchivoFotoMaximo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertencia.
        /// </summary>
        public static string EtiquetaTituloAdvertencia {
            get {
                return ResourceManager.GetString("EtiquetaTituloAdvertencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar contenido del párrafo.
        /// </summary>
        public static string EtiquetaTituloConfirmar {
            get {
                return ResourceManager.GetString("EtiquetaTituloConfirmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string EtiquetaTituloError {
            get {
                return ResourceManager.GetString("EtiquetaTituloError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El registro seleccionado ya está registrado.
        /// </summary>
        public static string ExistenciaRegistro {
            get {
                return ResourceManager.GetString("ExistenciaRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar al menos un filtro de búsqueda..
        /// </summary>
        public static string InformacionIngresarFiltro {
            get {
                return ResourceManager.GetString("InformacionIngresarFiltro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La información mostrada corresponde a la.
        /// </summary>
        public static string InformacionPreFiltro {
            get {
                return ResourceManager.GetString("InformacionPreFiltro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La solicitud no ha podido ser procesada. Comuníquese con el Administrador del Sistema..
        /// </summary>
        public static string MensajeException {
            get {
                return ResourceManager.GetString("MensajeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualmente no hay Observaciones para la Auditoría..
        /// </summary>
        public static string MensajeObservacionAuditoria {
            get {
                return ResourceManager.GetString("MensajeObservacionAuditoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe Ingresar valores mayores a 0.
        /// </summary>
        public static string MensajeValidacionMayores {
            get {
                return ResourceManager.GetString("MensajeValidacionMayores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese los Campos que son Obligatorios..
        /// </summary>
        public static string MensajeVerificarCamposObligatorios {
            get {
                return ResourceManager.GetString("MensajeVerificarCamposObligatorios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro de eliminar el registro?.
        /// </summary>
        public static string MsgEliminacion {
            get {
                return ResourceManager.GetString("MsgEliminacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro de Eliminar los Registros?.
        /// </summary>
        public static string MsgEliminacionList {
            get {
                return ResourceManager.GetString("MsgEliminacionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El registro se encuentra activo..
        /// </summary>
        public static string MsgRegistroActivo {
            get {
                return ResourceManager.GetString("MsgRegistroActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El registro se encuentra inactivo..
        /// </summary>
        public static string MsgRegistroInactivo {
            get {
                return ResourceManager.GetString("MsgRegistroInactivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primero debe registrar la Sección Principal {0}..
        /// </summary>
        public static string MsgValidarTabPrincipal {
            get {
                return ResourceManager.GetString("MsgValidarTabPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verificar: Ingrese los Campos que son Obligatorios..
        /// </summary>
        public static string MsgValideCampos {
            get {
                return ResourceManager.GetString("MsgValideCampos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar un archivo, verifique..
        /// </summary>
        public static string MsjValidaEligeArchivo {
            get {
                return ResourceManager.GetString("MsjValidaEligeArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El archivo elegido no tiene la extensión permitida, verifique..
        /// </summary>
        public static string MsjValidaExtensionArchivo {
            get {
                return ResourceManager.GetString("MsjValidaExtensionArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los registros seleccionados no coinciden:.
        /// </summary>
        public static string RegistrosNoCoinciden {
            get {
                return ResourceManager.GetString("RegistrosNoCoinciden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se anuló registro con éxito..
        /// </summary>
        public static string SeAnuloRegistro {
            get {
                return ResourceManager.GetString("SeAnuloRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se eliminó el registro con éxito..
        /// </summary>
        public static string SeEliminoInformacionExito {
            get {
                return ResourceManager.GetString("SeEliminoInformacionExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se guardó la información con éxito..
        /// </summary>
        public static string SeGuardoInformacionExito {
            get {
                return ResourceManager.GetString("SeGuardoInformacionExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar al menos un registro para eliminar..
        /// </summary>
        public static string SeleccionarRegistroEliminar {
            get {
                return ResourceManager.GetString("SeleccionarRegistroEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Al menos un parámetro de filtro correcto.
        /// </summary>
        public static string SeleccioneFiltro {
            get {
                return ResourceManager.GetString("SeleccioneFiltro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se reactivó el registro con éxito..
        /// </summary>
        public static string SeReactivoInformacionExito {
            get {
                return ResourceManager.GetString("SeReactivoInformacionExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe Seleccionar al Menos Uno de los Siguientes Campos.
        /// </summary>
        public static string ValidarCamposAlMenosUno {
            get {
                return ResourceManager.GetString("ValidarCamposAlMenosUno", resourceCulture);
            }
        }
    }
}
