//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34003
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pe.ElectroPeru.SGI.Presentacion.Recursos.Base {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BuscadorEmpresaResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BuscadorEmpresaResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pe.ElectroPeru.SGI.Presentacion.Recursos.Base.BuscadorEmpresaResource", typeof(BuscadorEmpresaResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar Por.
        /// </summary>
        public static string EtiquetaBuscarPor {
            get {
                return ResourceManager.GetString("EtiquetaBuscarPor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código Tipo Empresa.
        /// </summary>
        public static string EtiquetaCodigoTipoEmpresa {
            get {
                return ResourceManager.GetString("EtiquetaCodigoTipoEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de Documento (RUC).
        /// </summary>
        public static string EtiquetaDocumento {
            get {
                return ResourceManager.GetString("EtiquetaDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar Empresa.
        /// </summary>
        public static string EtiquetaFormularioBuscarEmpresa {
            get {
                return ResourceManager.GetString("EtiquetaFormularioBuscarEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese mínimo tres caracteres.
        /// </summary>
        public static string EtiquetaIngresoCaracteres {
            get {
                return ResourceManager.GetString("EtiquetaIngresoCaracteres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede registrar la empresa, ya existe una con el mismo RUC.
        /// </summary>
        public static string EtiquetaMensajeValidacion1 {
            get {
                return ResourceManager.GetString("EtiquetaMensajeValidacion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede registrar la empresa, ya existe una con la misma razón social.
        /// </summary>
        public static string EtiquetaMensajeValidacion2 {
            get {
                return ResourceManager.GetString("EtiquetaMensajeValidacion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede registrar la empresa, ya existe una con el mismo RUC y razón social.
        /// </summary>
        public static string EtiquetaMensajeValidacion3 {
            get {
                return ResourceManager.GetString("EtiquetaMensajeValidacion3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Razón Social.
        /// </summary>
        public static string EtiquetaRazonSocial {
            get {
                return ResourceManager.GetString("EtiquetaRazonSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RUC.
        /// </summary>
        public static string EtiquetaRuc {
            get {
                return ResourceManager.GetString("EtiquetaRuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar.
        /// </summary>
        public static string EtiquetaTabAgregar {
            get {
                return ResourceManager.GetString("EtiquetaTabAgregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Búsqueda.
        /// </summary>
        public static string EtiquetaTabBusqueda {
            get {
                return ResourceManager.GetString("EtiquetaTabBusqueda", resourceCulture);
            }
        }
    }
}
