//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pe.ElectroPeru.SGI.Presentacion.Recursos.Base {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GenericoResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GenericoResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pe.ElectroPeru.SGI.Presentacion.Recursos.Base.GenericoResource", typeof(GenericoResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ACEPTAR.
        /// </summary>
        public static string BotonAceptar {
            get {
                return ResourceManager.GetString("BotonAceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar.
        /// </summary>
        public static string BotonAgregar {
            get {
                return ResourceManager.GetString("BotonAgregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir.
        /// </summary>
        public static string BotonAñadir {
            get {
                return ResourceManager.GetString("BotonAñadir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anterior.
        /// </summary>
        public static string BotonAnterior {
            get {
                return ResourceManager.GetString("BotonAnterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ANULAR.
        /// </summary>
        public static string BotonAnular {
            get {
                return ResourceManager.GetString("BotonAnular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aplica.
        /// </summary>
        public static string BotonAplica {
            get {
                return ResourceManager.GetString("BotonAplica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aprobar.
        /// </summary>
        public static string BotonAprobar {
            get {
                return ResourceManager.GetString("BotonAprobar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autorizar.
        /// </summary>
        public static string BotonAutorizar {
            get {
                return ResourceManager.GetString("BotonAutorizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BUSCAR.
        /// </summary>
        public static string BotonBuscar {
            get {
                return ResourceManager.GetString("BotonBuscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Búsqueda Avanzada.
        /// </summary>
        public static string BotonBusquedaAvanzada {
            get {
                return ResourceManager.GetString("BotonBusquedaAvanzada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CANCELAR.
        /// </summary>
        public static string BotonCancelar {
            get {
                return ResourceManager.GetString("BotonCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CERRAR.
        /// </summary>
        public static string BotonCerrar {
            get {
                return ResourceManager.GetString("BotonCerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar sesión.
        /// </summary>
        public static string BotonCerrarSesion {
            get {
                return ResourceManager.GetString("BotonCerrarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copiar.
        /// </summary>
        public static string BotonCopiar {
            get {
                return ResourceManager.GetString("BotonCopiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Denegar.
        /// </summary>
        public static string BotonDenegar {
            get {
                return ResourceManager.GetString("BotonDenegar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descargar Excel.
        /// </summary>
        public static string BotonDescargarExcel {
            get {
                return ResourceManager.GetString("BotonDescargarExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descargar PDF.
        /// </summary>
        public static string BotonDescargarPDF {
            get {
                return ResourceManager.GetString("BotonDescargarPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string BotonEliminar {
            get {
                return ResourceManager.GetString("BotonEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finalizar Contrato.
        /// </summary>
        public static string BotonFinalizarContrato {
            get {
                return ResourceManager.GetString("BotonFinalizarContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GUARDAR.
        /// </summary>
        public static string BotonGrabar {
            get {
                return ResourceManager.GetString("BotonGrabar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GUARDAR.
        /// </summary>
        public static string BotonGuardar {
            get {
                return ResourceManager.GetString("BotonGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LIMPIAR.
        /// </summary>
        public static string BotonLimpiar {
            get {
                return ResourceManager.GetString("BotonLimpiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mostrar.
        /// </summary>
        public static string BotonMostrar {
            get {
                return ResourceManager.GetString("BotonMostrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No Aplica.
        /// </summary>
        public static string BotonNoAplica {
            get {
                return ResourceManager.GetString("BotonNoAplica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rechazar.
        /// </summary>
        public static string BotonRechazar {
            get {
                return ResourceManager.GetString("BotonRechazar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Responder.
        /// </summary>
        public static string BotonResponder {
            get {
                return ResourceManager.GetString("BotonResponder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SALIR.
        /// </summary>
        public static string BotonSalir {
            get {
                return ResourceManager.GetString("BotonSalir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar.
        /// </summary>
        public static string BotonSeleccionar {
            get {
                return ResourceManager.GetString("BotonSeleccionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Siguiente.
        /// </summary>
        public static string BotonSiguiente {
            get {
                return ResourceManager.GetString("BotonSiguiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vista Previa.
        /// </summary>
        public static string BotonVistaPrevia {
            get {
                return ResourceManager.GetString("BotonVistaPrevia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descargar Excel.
        /// </summary>
        public static string BtnDescargarExcel {
            get {
                return ResourceManager.GetString("BtnDescargarExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regresar.
        /// </summary>
        public static string BtnRegresar {
            get {
                return ResourceManager.GetString("BtnRegresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ACTIVA.
        /// </summary>
        public static string EtiquetaActiva {
            get {
                return ResourceManager.GetString("EtiquetaActiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BUSCAR.
        /// </summary>
        public static string EtiquetaBuscar {
            get {
                return ResourceManager.GetString("EtiquetaBuscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Caracteres.
        /// </summary>
        public static string EtiquetaCaracteres {
            get {
                return ResourceManager.GetString("EtiquetaCaracteres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copiar Plantilla.
        /// </summary>
        public static string EtiquetaCopiarPlantilla {
            get {
                return ResourceManager.GetString("EtiquetaCopiarPlantilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo Electronico.
        /// </summary>
        public static string EtiquetaCorreoElectronico {
            get {
                return ResourceManager.GetString("EtiquetaCorreoElectronico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Costo (US$).
        /// </summary>
        public static string EtiquetaCosto {
            get {
                return ResourceManager.GetString("EtiquetaCosto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        public static string EtiquetaEditar {
            get {
                return ResourceManager.GetString("EtiquetaEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar contrato.
        /// </summary>
        public static string EtiquetaEditarContenidoContrato {
            get {
                return ResourceManager.GetString("EtiquetaEditarContenidoContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elemento Duplicado.
        /// </summary>
        public static string EtiquetaElementoDuplicado {
            get {
                return ResourceManager.GetString("EtiquetaElementoDuplicado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string EtiquetaEliminar {
            get {
                return ResourceManager.GetString("EtiquetaEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay información disponible para descargar.
        /// </summary>
        public static string EtiquetaExportarTablaSinRegistro {
            get {
                return ResourceManager.GetString("EtiquetaExportarTablaSinRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        public static string EtiquetaFecha {
            get {
                return ResourceManager.GetString("EtiquetaFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Actividad.
        /// </summary>
        public static string EtiquetaFechaActividad {
            get {
                return ResourceManager.GetString("EtiquetaFechaActividad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a *** FIN DE {0} ***.
        /// </summary>
        public static string EtiquetaFinReporte {
            get {
                return ResourceManager.GetString("EtiquetaFinReporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formulario Anexo.
        /// </summary>
        public static string EtiquetaFormularioAnexo {
            get {
                return ResourceManager.GetString("EtiquetaFormularioAnexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formulario Causa Raiz.
        /// </summary>
        public static string EtiquetaFormularioCausaRaiz {
            get {
                return ResourceManager.GetString("EtiquetaFormularioCausaRaiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formulario Foto.
        /// </summary>
        public static string EtiquetaFormularioFoto {
            get {
                return ResourceManager.GetString("EtiquetaFormularioFoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formulario de Ingreso de Acciones.
        /// </summary>
        public static string EtiquetaFormularioIngresoAcciones {
            get {
                return ResourceManager.GetString("EtiquetaFormularioIngresoAcciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargar Archivo.
        /// </summary>
        public static string EtiquetaGridFileUpload {
            get {
                return ResourceManager.GetString("EtiquetaGridFileUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anterior.
        /// </summary>
        public static string EtiquetaGrillaBotonAnterior {
            get {
                return ResourceManager.GetString("EtiquetaGrillaBotonAnterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Siguiente.
        /// </summary>
        public static string EtiquetaGrillaBotonSiguiente {
            get {
                return ResourceManager.GetString("EtiquetaGrillaBotonSiguiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mostrar {0} filas.
        /// </summary>
        public static string EtiquetaGrillaMostrarFilas {
            get {
                return ResourceManager.GetString("EtiquetaGrillaMostrarFilas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay información disponible en la tabla.
        /// </summary>
        public static string EtiquetaGrillaTablaSinRegistro {
            get {
                return ResourceManager.GetString("EtiquetaGrillaTablaSinRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imagen.
        /// </summary>
        public static string EtiquetaImagen {
            get {
                return ResourceManager.GetString("EtiquetaImagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INACTIVA.
        /// </summary>
        public static string EtiquetaInactiva {
            get {
                return ResourceManager.GetString("EtiquetaInactiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar Fotos.
        /// </summary>
        public static string EtiquetaIngresarFotos {
            get {
                return ResourceManager.GetString("EtiquetaIngresarFotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Limpiar.
        /// </summary>
        public static string EtiquetaLimpiar {
            get {
                return ResourceManager.GetString("EtiquetaLimpiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista.
        /// </summary>
        public static string EtiquetaLista {
            get {
                return ResourceManager.GetString("EtiquetaLista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Máx..
        /// </summary>
        public static string EtiquetaMaximoAbreviado {
            get {
                return ResourceManager.GetString("EtiquetaMaximoAbreviado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Máx..
        /// </summary>
        public static string EtiquetaMaximoAbreviado1 {
            get {
                return ResourceManager.GetString("EtiquetaMaximoAbreviado1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Máx. {0} caracteres.
        /// </summary>
        public static string EtiquetaMaximoCaracteres {
            get {
                return ResourceManager.GetString("EtiquetaMaximoCaracteres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NO.
        /// </summary>
        public static string EtiquetaNo {
            get {
                return ResourceManager.GetString("EtiquetaNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notificaciones.
        /// </summary>
        public static string EtiquetaNotificaciones {
            get {
                return ResourceManager.GetString("EtiquetaNotificaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notificar.
        /// </summary>
        public static string EtiquetaNotificar {
            get {
                return ResourceManager.GetString("EtiquetaNotificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número.
        /// </summary>
        public static string EtiquetaNumero {
            get {
                return ResourceManager.GetString("EtiquetaNumero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio Unitario (US$/h).
        /// </summary>
        public static string EtiquetaPrecioUnitario {
            get {
                return ResourceManager.GetString("EtiquetaPrecioUnitario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reenviar.
        /// </summary>
        public static string EtiquetaReenviar {
            get {
                return ResourceManager.GetString("EtiquetaReenviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Responder.
        /// </summary>
        public static string EtiquetaResponder {
            get {
                return ResourceManager.GetString("EtiquetaResponder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resultados de Búsqueda.
        /// </summary>
        public static string EtiquetaResultadosBusqueda {
            get {
                return ResourceManager.GetString("EtiquetaResultadosBusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (SELECCIONAR).
        /// </summary>
        public static string EtiquetaSeleccionar {
            get {
                return ResourceManager.GetString("EtiquetaSeleccionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SÍ.
        /// </summary>
        public static string EtiquetaSi {
            get {
                return ResourceManager.GetString("EtiquetaSi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sí, Eliminar.
        /// </summary>
        public static string EtiquetaSiEliminar {
            get {
                return ResourceManager.GetString("EtiquetaSiEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sí, Grabar.
        /// </summary>
        public static string EtiquetaSiGrabar {
            get {
                return ResourceManager.GetString("EtiquetaSiGrabar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tabla.
        /// </summary>
        public static string EtiquetaTabla {
            get {
                return ResourceManager.GetString("EtiquetaTabla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El tamaño del archivo no debe exceder los {0} MB.
        /// </summary>
        public static string EtiquetaTamanioArchivo {
            get {
                return ResourceManager.GetString("EtiquetaTamanioArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anexo.
        /// </summary>
        public static string EtiquetaTelefonoAnexo {
            get {
                return ResourceManager.GetString("EtiquetaTelefonoAnexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono Movil.
        /// </summary>
        public static string EtiquetaTelefonoMovil {
            get {
                return ResourceManager.GetString("EtiquetaTelefonoMovil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono Trabajo.
        /// </summary>
        public static string EtiquetaTelefonoTrabajo {
            get {
                return ResourceManager.GetString("EtiquetaTelefonoTrabajo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Texto.
        /// </summary>
        public static string EtiquetaTexto {
            get {
                return ResourceManager.GetString("EtiquetaTexto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiempo (h).
        /// </summary>
        public static string EtiquetaTiempo {
            get {
                return ResourceManager.GetString("EtiquetaTiempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los tipos de archivos deben ser BMP, GIF, JPEG, TIF, TIFF o PNG.
        /// </summary>
        public static string EtiquetaTipoArchivoFoto {
            get {
                return ResourceManager.GetString("EtiquetaTipoArchivoFoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Común.
        /// </summary>
        public static string EtiquetaTipoParametroComun {
            get {
                return ResourceManager.GetString("EtiquetaTipoParametroComun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Funcional.
        /// </summary>
        public static string EtiquetaTipoParametroFuncional {
            get {
                return ResourceManager.GetString("EtiquetaTipoParametroFuncional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sistema.
        /// </summary>
        public static string EtiquetaTipoParametroSistema {
            get {
                return ResourceManager.GetString("EtiquetaTipoParametroSistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Advertencia.
        /// </summary>
        public static string EtiquetaTituloAdvertencia {
            get {
                return ResourceManager.GetString("EtiquetaTituloAdvertencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar.
        /// </summary>
        public static string EtiquetaTituloConfirmar {
            get {
                return ResourceManager.GetString("EtiquetaTituloConfirmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar Registro.
        /// </summary>
        public static string EtiquetaTituloEliminar {
            get {
                return ResourceManager.GetString("EtiquetaTituloEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información.
        /// </summary>
        public static string EtiquetaTituloInformacion {
            get {
                return ResourceManager.GetString("EtiquetaTituloInformacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (TODOS).
        /// </summary>
        public static string EtiquetaTodos {
            get {
                return ResourceManager.GetString("EtiquetaTodos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vencido.
        /// </summary>
        public static string EtiquetaVencido {
            get {
                return ResourceManager.GetString("EtiquetaVencido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verificar.
        /// </summary>
        public static string EtiquetaVerificar {
            get {
                return ResourceManager.GetString("EtiquetaVerificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vigente.
        /// </summary>
        public static string EtiquetaVigente {
            get {
                return ResourceManager.GetString("EtiquetaVigente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visualizar.
        /// </summary>
        public static string EtiquetaVisualizar {
            get {
                return ResourceManager.GetString("EtiquetaVisualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acciones.
        /// </summary>
        public static string GridAcciones {
            get {
                return ResourceManager.GetString("GridAcciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adjuntos.
        /// </summary>
        public static string GridAdjunto {
            get {
                return ResourceManager.GetString("GridAdjunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Valores.
        /// </summary>
        public static string GridAgregarValores {
            get {
                return ResourceManager.GetString("GridAgregarValores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AgregarVariable.
        /// </summary>
        public static string GridAgregarVariable {
            get {
                return ResourceManager.GetString("GridAgregarVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aprobar.
        /// </summary>
        public static string GridAprobar {
            get {
                return ResourceManager.GetString("GridAprobar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar Acción.
        /// </summary>
        public static string GridCerrarAccion {
            get {
                return ResourceManager.GetString("GridCerrarAccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultar.
        /// </summary>
        public static string GridConsulta {
            get {
                return ResourceManager.GetString("GridConsulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contrato.
        /// </summary>
        public static string GridContrato {
            get {
                return ResourceManager.GetString("GridContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Controles.
        /// </summary>
        public static string GridControles {
            get {
                return ResourceManager.GetString("GridControles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copiar.
        /// </summary>
        public static string GridCopiar {
            get {
                return ResourceManager.GetString("GridCopiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copiar Estadios.
        /// </summary>
        public static string GridCopiarEstadio {
            get {
                return ResourceManager.GetString("GridCopiarEstadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descargar.
        /// </summary>
        public static string GridDescargar {
            get {
                return ResourceManager.GetString("GridDescargar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descargar Anexo.
        /// </summary>
        public static string GridDescargarAnexo {
            get {
                return ResourceManager.GetString("GridDescargarAnexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descargar Foto.
        /// </summary>
        public static string GridDescargarFoto {
            get {
                return ResourceManager.GetString("GridDescargarFoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AI.
        /// </summary>
        public static string GridDescargarIncidente {
            get {
                return ResourceManager.GetString("GridDescargarIncidente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IF.
        /// </summary>
        public static string GridDescargarInvestigacion {
            get {
                return ResourceManager.GetString("GridDescargarInvestigacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver Detalle.
        /// </summary>
        public static string GridDetalle {
            get {
                return ResourceManager.GetString("GridDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver AEI (Asociadas).
        /// </summary>
        public static string GridDetalleAEI {
            get {
                return ResourceManager.GetString("GridDetalleAEI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver Indicador (Asociados).
        /// </summary>
        public static string GridDetalleIndicador {
            get {
                return ResourceManager.GetString("GridDetalleIndicador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver OEC (Asociados).
        /// </summary>
        public static string GridDetalleOEC {
            get {
                return ResourceManager.GetString("GridDetalleOEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver OEE (Asociados).
        /// </summary>
        public static string GridDetalleOEE {
            get {
                return ResourceManager.GetString("GridDetalleOEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        public static string GridEditar {
            get {
                return ResourceManager.GetString("GridEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string GridEliminar {
            get {
                return ResourceManager.GetString("GridEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estadios.
        /// </summary>
        public static string GridEstadios {
            get {
                return ResourceManager.GetString("GridEstadios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Excel.
        /// </summary>
        public static string GridExcel {
            get {
                return ResourceManager.GetString("GridExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observar.
        /// </summary>
        public static string GridObservacion {
            get {
                return ResourceManager.GetString("GridObservacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Párrafos.
        /// </summary>
        public static string GridParrafo {
            get {
                return ResourceManager.GetString("GridParrafo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PDF.
        /// </summary>
        public static string GridPdf {
            get {
                return ResourceManager.GetString("GridPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Predecesora.
        /// </summary>
        public static string GridPredecesora {
            get {
                return ResourceManager.GetString("GridPredecesora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reactivar.
        /// </summary>
        public static string GridReactivar {
            get {
                return ResourceManager.GetString("GridReactivar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar Notas.
        /// </summary>
        public static string GridRegistrarNotas {
            get {
                return ResourceManager.GetString("GridRegistrarNotas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro Seguimiento.
        /// </summary>
        public static string GridRegistroSeguimiento {
            get {
                return ResourceManager.GetString("GridRegistroSeguimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reporte Registro.
        /// </summary>
        public static string GridReporteRecord {
            get {
                return ResourceManager.GetString("GridReporteRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reportes.
        /// </summary>
        public static string GridReportes {
            get {
                return ResourceManager.GetString("GridReportes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Revisar.
        /// </summary>
        public static string GridRevisar {
            get {
                return ResourceManager.GetString("GridRevisar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar Equipos.
        /// </summary>
        public static string GridSeleccionarEquipos {
            get {
                return ResourceManager.GetString("GridSeleccionarEquipos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar Personas.
        /// </summary>
        public static string GridSeleccionarPersonas {
            get {
                return ResourceManager.GetString("GridSeleccionarPersonas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar Procesos.
        /// </summary>
        public static string GridSeleccionarProcesos {
            get {
                return ResourceManager.GetString("GridSeleccionarProcesos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar SubProcesos.
        /// </summary>
        public static string GridSeleccionarSubProcesos {
            get {
                return ResourceManager.GetString("GridSeleccionarSubProcesos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor Alquiler.
        /// </summary>
        public static string GridValorAlquiler {
            get {
                return ResourceManager.GetString("GridValorAlquiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver Acción.
        /// </summary>
        public static string GridVerAccion {
            get {
                return ResourceManager.GetString("GridVerAccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver Historial de Cambios.
        /// </summary>
        public static string GridVerHistorialInvestigacion {
            get {
                return ResourceManager.GetString("GridVerHistorialInvestigacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver Seguimiento.
        /// </summary>
        public static string GridVerSeguimiento {
            get {
                return ResourceManager.GetString("GridVerSeguimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vista Previa.
        /// </summary>
        public static string GridVistaPrevia {
            get {
                return ResourceManager.GetString("GridVistaPrevia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese los Campos Obligatorios.
        /// </summary>
        public static string MsgValideCampos {
            get {
                return ResourceManager.GetString("MsgValideCampos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GESTIÓN DE INDICADORES.
        /// </summary>
        public static string NombreSistema {
            get {
                return ResourceManager.GetString("NombreSistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adjuntos.
        /// </summary>
        public static string TituloAdjuntos {
            get {
                return ResourceManager.GetString("TituloAdjuntos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe ingresar al menos un valor.
        /// </summary>
        public static string ValidacionAlmenosUno {
            get {
                return ResourceManager.GetString("ValidacionAlmenosUno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ningún Campo puede tener números negativos.
        /// </summary>
        public static string ValidacionNumeroNegativo {
            get {
                return ResourceManager.GetString("ValidacionNumeroNegativo", resourceCulture);
            }
        }
    }
}
