//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pe.ElectroPeru.SGI.Presentacion.Recursos.Mantenimiento.Perspectiva {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PerspectivaResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PerspectivaResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pe.ElectroPeru.SGI.Presentacion.Recursos.Mantenimiento.Perspectiva.PerspectivaRes" +
                            "ource", typeof(PerspectivaResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Perspectiva.
        /// </summary>
        public static string BotonAgregarPerspectiva {
            get {
                return ResourceManager.GetString("BotonAgregarPerspectiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Área.
        /// </summary>
        public static string EtiquetaArea {
            get {
                return ResourceManager.GetString("EtiquetaArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ELIMINAR.
        /// </summary>
        public static string EtiquetaBotonEliminar {
            get {
                return ResourceManager.GetString("EtiquetaBotonEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GRABAR.
        /// </summary>
        public static string EtiquetaBotonGuardar {
            get {
                return ResourceManager.GetString("EtiquetaBotonGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción Perspectiva.
        /// </summary>
        public static string EtiquetaDescripcion {
            get {
                return ResourceManager.GetString("EtiquetaDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción Perspectiva.
        /// </summary>
        public static string EtiquetaDescripcionPerspectiva {
            get {
                return ResourceManager.GetString("EtiquetaDescripcionPerspectiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Indicador.
        /// </summary>
        public static string EtiquetaIndicador {
            get {
                return ResourceManager.GetString("EtiquetaIndicador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista.
        /// </summary>
        public static string EtiquetaLista {
            get {
                return ResourceManager.GetString("EtiquetaLista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea eliminar la Perspectiva?.
        /// </summary>
        public static string EtiquetaMensajeEliminar {
            get {
                return ResourceManager.GetString("EtiquetaMensajeEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre Perspectiva.
        /// </summary>
        public static string EtiquetaNombre {
            get {
                return ResourceManager.GetString("EtiquetaNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre Perspectiva.
        /// </summary>
        public static string EtiquetaNombrePerspectiva {
            get {
                return ResourceManager.GetString("EtiquetaNombrePerspectiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Objetivo Estratégico FONAFE.
        /// </summary>
        public static string EtiquetaObjetivoEstrategicoFonafe {
            get {
                return ResourceManager.GetString("EtiquetaObjetivoEstrategicoFonafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Responsable.
        /// </summary>
        public static string EtiquetaResponsable {
            get {
                return ResourceManager.GetString("EtiquetaResponsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generales.
        /// </summary>
        public static string EtiquetaTabGenerales {
            get {
                return ResourceManager.GetString("EtiquetaTabGenerales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Objetivo Estratégico Fonafe Asociados.
        /// </summary>
        public static string EtiquetaTabObjetivoEstrategicoFonafeDetalle {
            get {
                return ResourceManager.GetString("EtiquetaTabObjetivoEstrategicoFonafeDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo.
        /// </summary>
        public static string EtiquetaTipo {
            get {
                return ResourceManager.GetString("EtiquetaTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BANDEJA DE PERSPECTIVA.
        /// </summary>
        public static string EtiquetaTituloBandeja {
            get {
                return ResourceManager.GetString("EtiquetaTituloBandeja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información General.
        /// </summary>
        public static string EtiquetaTituloInformacionGeneral {
            get {
                return ResourceManager.GetString("EtiquetaTituloInformacionGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INGRESO DE PERSPECTIVA.
        /// </summary>
        public static string EtiquetaTituloPerspectiva {
            get {
                return ResourceManager.GetString("EtiquetaTituloPerspectiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción Perspectiva.
        /// </summary>
        public static string GridDescripcionPerspectiva {
            get {
                return ResourceManager.GetString("GridDescripcionPerspectiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        public static string GridEstado {
            get {
                return ResourceManager.GetString("GridEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Indicador.
        /// </summary>
        public static string GridIndicador {
            get {
                return ResourceManager.GetString("GridIndicador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre Perspectiva.
        /// </summary>
        public static string GridNombrePerspectiva {
            get {
                return ResourceManager.GetString("GridNombrePerspectiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perspectiva.
        /// </summary>
        public static string GridObjetivoEstrategicoFonafe {
            get {
                return ResourceManager.GetString("GridObjetivoEstrategicoFonafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Responsable.
        /// </summary>
        public static string GridResponsable {
            get {
                return ResourceManager.GetString("GridResponsable", resourceCulture);
            }
        }
    }
}
