//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pe.ElectroPeru.SGI.Presentacion.Recursos.Reportes.Dashboard {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DashboardResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DashboardResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pe.ElectroPeru.SGI.Presentacion.Recursos.Reportes.Dashboard.DashboardResource", typeof(DashboardResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Año.
        /// </summary>
        public static string EtiquetaAnio {
            get {
                return ResourceManager.GetString("EtiquetaAnio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar.
        /// </summary>
        public static string EtiquetaBotonConsultar {
            get {
                return ResourceManager.GetString("EtiquetaBotonConsultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard de Indicadores.
        /// </summary>
        public static string EtiquetaContenido {
            get {
                return ResourceManager.GetString("EtiquetaContenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Día.
        /// </summary>
        public static string EtiquetaDia {
            get {
                return ResourceManager.GetString("EtiquetaDia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtro.
        /// </summary>
        public static string EtiquetaFiltroPeriodicidad {
            get {
                return ResourceManager.GetString("EtiquetaFiltroPeriodicidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicador.
        /// </summary>
        public static string EtiquetaIndicador {
            get {
                return ResourceManager.GetString("EtiquetaIndicador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mes.
        /// </summary>
        public static string EtiquetaMes {
            get {
                return ResourceManager.GetString("EtiquetaMes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Periodicidad.
        /// </summary>
        public static string EtiquetaTipoPeriodicidad {
            get {
                return ResourceManager.GetString("EtiquetaTipoPeriodicidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard de Indicadores.
        /// </summary>
        public static string EtiquetaTituloPrincipal {
            get {
                return ResourceManager.GetString("EtiquetaTituloPrincipal", resourceCulture);
            }
        }
    }
}
