//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pe.ElectroPeru.SGI.Presentacion.Recursos.Seguimiento {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccionResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccionResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pe.ElectroPeru.SGI.Presentacion.Recursos.Seguimiento.AccionResource", typeof(AccionResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ANULAR POR GERENCIA.
        /// </summary>
        public static string BotonAnuladoGerencia {
            get {
                return ResourceManager.GetString("BotonAnuladoGerencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CERRAR POR GERENCIA.
        /// </summary>
        public static string BotonCerradoGerencia {
            get {
                return ResourceManager.GetString("BotonCerradoGerencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a REABIERTO POR GERENCIA.
        /// </summary>
        public static string BotonReabiertoGerencia {
            get {
                return ResourceManager.GetString("BotonReabiertoGerencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acciones correctivas.
        /// </summary>
        public static string EtiquetaAccionesCorrectivas {
            get {
                return ResourceManager.GetString("EtiquetaAccionesCorrectivas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acción Planteada Por.
        /// </summary>
        public static string EtiquetaActionRaised {
            get {
                return ResourceManager.GetString("EtiquetaActionRaised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solo acciones.
        /// </summary>
        public static string EtiquetaActions {
            get {
                return ResourceManager.GetString("EtiquetaActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comportamiento.
        /// </summary>
        public static string EtiquetaActionsMenu {
            get {
                return ResourceManager.GetString("EtiquetaActionsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Archivo.
        /// </summary>
        public static string EtiquetaAgregarArchivo {
            get {
                return ResourceManager.GetString("EtiquetaAgregarArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar / Cambiar foto.
        /// </summary>
        public static string EtiquetaAgregarCambiarFoto {
            get {
                return ResourceManager.GetString("EtiquetaAgregarCambiarFoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alerta.
        /// </summary>
        public static string EtiquetaAlerta {
            get {
                return ResourceManager.GetString("EtiquetaAlerta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anulado por Gerencia.
        /// </summary>
        public static string EtiquetaAlertaPlomo {
            get {
                return ResourceManager.GetString("EtiquetaAlertaPlomo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fuera de fecha.
        /// </summary>
        public static string EtiquetaAlertaRojo {
            get {
                return ResourceManager.GetString("EtiquetaAlertaRojo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En fecha.
        /// </summary>
        public static string EtiquetaAlertaVerde {
            get {
                return ResourceManager.GetString("EtiquetaAlertaVerde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anexo.
        /// </summary>
        public static string EtiquetaAnexo {
            get {
                return ResourceManager.GetString("EtiquetaAnexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Area.
        /// </summary>
        public static string EtiquetaArea {
            get {
                return ResourceManager.GetString("EtiquetaArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir foto.
        /// </summary>
        public static string EtiquetaBotonAgregarFoto {
            get {
                return ResourceManager.GetString("EtiquetaBotonAgregarFoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CANCELAR.
        /// </summary>
        public static string EtiquetaBotonCancelar {
            get {
                return ResourceManager.GetString("EtiquetaBotonCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GUARDAR.
        /// </summary>
        public static string EtiquetaBotonGuardar {
            get {
                return ResourceManager.GetString("EtiquetaBotonGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BUSCAR.
        /// </summary>
        public static string EtiquetaBuscar {
            get {
                return ResourceManager.GetString("EtiquetaBuscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Búsqueda Avanzada.
        /// </summary>
        public static string EtiquetaBusquedaA {
            get {
                return ResourceManager.GetString("EtiquetaBusquedaA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Búsqueda Rápida.
        /// </summary>
        public static string EtiquetaBusquedaRapida {
            get {
                return ResourceManager.GetString("EtiquetaBusquedaRapida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categoría o Clasificación Principal del Incidente.
        /// </summary>
        public static string EtiquetaCategoriaIncidente {
            get {
                return ResourceManager.GetString("EtiquetaCategoriaIncidente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrado por.
        /// </summary>
        public static string EtiquetaCerradoPor {
            get {
                return ResourceManager.GetString("EtiquetaCerradoPor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clasificación:.
        /// </summary>
        public static string EtiquetaClassification {
            get {
                return ResourceManager.GetString("EtiquetaClassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrado.
        /// </summary>
        public static string EtiquetaClosed {
            get {
                return ResourceManager.GetString("EtiquetaClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrado por.
        /// </summary>
        public static string EtiquetaClosedBy {
            get {
                return ResourceManager.GetString("EtiquetaClosedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrado en.
        /// </summary>
        public static string EtiquetaClosedOn {
            get {
                return ResourceManager.GetString("EtiquetaClosedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario que realizó el seguimiento.
        /// </summary>
        public static string EtiquetaColaborador {
            get {
                return ResourceManager.GetString("EtiquetaColaborador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comentario (Especificar a detalle).
        /// </summary>
        public static string EtiquetaComentario {
            get {
                return ResourceManager.GetString("EtiquetaComentario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comentario.
        /// </summary>
        public static string EtiquetaComment {
            get {
                return ResourceManager.GetString("EtiquetaComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empresa / Contratista:.
        /// </summary>
        public static string EtiquetaCompCont {
            get {
                return ResourceManager.GetString("EtiquetaCompCont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya completó la acción. ¿Desea cerrarla?.
        /// </summary>
        public static string EtiquetaCompletoAccion {
            get {
                return ResourceManager.GetString("EtiquetaCompletoAccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuración.
        /// </summary>
        public static string EtiquetaConfiguracion {
            get {
                return ResourceManager.GetString("EtiquetaConfiguracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pais:.
        /// </summary>
        public static string EtiquetaCountry {
            get {
                return ResourceManager.GetString("EtiquetaCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desde:.
        /// </summary>
        public static string EtiquetaD {
            get {
                return ResourceManager.GetString("EtiquetaD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        public static string EtiquetaDate {
            get {
                return ResourceManager.GetString("EtiquetaDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Departamento.
        /// </summary>
        public static string EtiquetaDepartamento {
            get {
                return ResourceManager.GetString("EtiquetaDepartamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string EtiquetaDescripcion {
            get {
                return ResourceManager.GetString("EtiquetaDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción de Anexo.
        /// </summary>
        public static string EtiquetaDescripcionAnexo {
            get {
                return ResourceManager.GetString("EtiquetaDescripcionAnexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción de Incidente.
        /// </summary>
        public static string EtiquetaDescripcionIncidente {
            get {
                return ResourceManager.GetString("EtiquetaDescripcionIncidente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de vencimiento.
        /// </summary>
        public static string EtiquetaDueDate {
            get {
                return ResourceManager.GetString("EtiquetaDueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar Foto.
        /// </summary>
        public static string EtiquetaEliminarFoto {
            get {
                return ResourceManager.GetString("EtiquetaEliminarFoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empresa.
        /// </summary>
        public static string EtiquetaEmpresa {
            get {
                return ResourceManager.GetString("EtiquetaEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        public static string EtiquetaEstado {
            get {
                return ResourceManager.GetString("EtiquetaEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        public static string EtiquetaEstadoAccion {
            get {
                return ResourceManager.GetString("EtiquetaEstadoAccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Cierre.
        /// </summary>
        public static string EtiquetaFechaCierre {
            get {
                return ResourceManager.GetString("EtiquetaFechaCierre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Estado.
        /// </summary>
        public static string EtiquetaFechaEstado {
            get {
                return ResourceManager.GetString("EtiquetaFechaEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Incidente.
        /// </summary>
        public static string EtiquetaFechaIncidente {
            get {
                return ResourceManager.GetString("EtiquetaFechaIncidente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Vencimiento Desde.
        /// </summary>
        public static string EtiquetaFechaVencimientoDesde {
            get {
                return ResourceManager.GetString("EtiquetaFechaVencimientoDesde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Vencimiento Hasta.
        /// </summary>
        public static string EtiquetaFechaVencimientoHasta {
            get {
                return ResourceManager.GetString("EtiquetaFechaVencimientoHasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mantenimiento de formularios.
        /// </summary>
        public static string EtiquetaFormMaintenance {
            get {
                return ResourceManager.GetString("EtiquetaFormMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Foto.
        /// </summary>
        public static string EtiquetaFoto {
            get {
                return ResourceManager.GetString("EtiquetaFoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mantenimiento de Grupo.
        /// </summary>
        public static string EtiquetaGroupMaintenance {
            get {
                return ResourceManager.GetString("EtiquetaGroupMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hasta:.
        /// </summary>
        public static string EtiquetaH {
            get {
                return ResourceManager.GetString("EtiquetaH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Herramienta.
        /// </summary>
        public static string EtiquetaHerramienta {
            get {
                return ResourceManager.GetString("EtiquetaHerramienta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hora de Incidente.
        /// </summary>
        public static string EtiquetaHoraIncidente {
            get {
                return ResourceManager.GetString("EtiquetaHoraIncidente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar Acciones.
        /// </summary>
        public static string EtiquetaIngresarAcciones {
            get {
                return ResourceManager.GetString("EtiquetaIngresarAcciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista.
        /// </summary>
        public static string EtiquetaLista {
            get {
                return ResourceManager.GetString("EtiquetaLista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista de Acciones.
        /// </summary>
        public static string EtiquetaListaAcciones {
            get {
                return ResourceManager.GetString("EtiquetaListaAcciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lugar Exacto.
        /// </summary>
        public static string EtiquetaLugarExacto {
            get {
                return ResourceManager.GetString("EtiquetaLugarExacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desea eliminar el registro seleccionado.
        /// </summary>
        public static string EtiquetaMensajeEliminarRegistro {
            get {
                return ResourceManager.GetString("EtiquetaMensajeEliminarRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Months.
        /// </summary>
        public static string EtiquetaMeses {
            get {
                return ResourceManager.GetString("EtiquetaMeses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actual Consecuencia del Incidente.
        /// </summary>
        public static string EtiquetaNivelIncidente {
            get {
                return ResourceManager.GetString("EtiquetaNivelIncidente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de Archivo.
        /// </summary>
        public static string EtiquetaNombreArchivo {
            get {
                return ResourceManager.GetString("EtiquetaNombreArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de Archivo.
        /// </summary>
        public static string EtiquetaNombreArchivoAnexo {
            get {
                return ResourceManager.GetString("EtiquetaNombreArchivoAnexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de Foto.
        /// </summary>
        public static string EtiquetaNombreFoto {
            get {
                return ResourceManager.GetString("EtiquetaNombreFoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva Empresa.
        /// </summary>
        public static string EtiquetaNuevaEmpresa {
            get {
                return ResourceManager.GetString("EtiquetaNuevaEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nro. Acción.
        /// </summary>
        public static string EtiquetaNumeroAccion {
            get {
                return ResourceManager.GetString("EtiquetaNumeroAccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nro. Registro.
        /// </summary>
        public static string EtiquetaNumeroRecord {
            get {
                return ResourceManager.GetString("EtiquetaNumeroRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reporte de Incidente Portal.
        /// </summary>
        public static string EtiquetaNumeroReportePortal {
            get {
                return ResourceManager.GetString("EtiquetaNumeroReportePortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nro. Record.
        /// </summary>
        public static string EtiquetaNumRecord {
            get {
                return ResourceManager.GetString("EtiquetaNumRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abrir solo informes.
        /// </summary>
        public static string EtiquetaOpenR {
            get {
                return ResourceManager.GetString("EtiquetaOpenR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Área de operación.
        /// </summary>
        public static string EtiquetaOperating {
            get {
                return ResourceManager.GetString("EtiquetaOperating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acciones Pendientes.
        /// </summary>
        public static string EtiquetaOutstanding {
            get {
                return ResourceManager.GetString("EtiquetaOutstanding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sobre Acciones.
        /// </summary>
        public static string EtiquetaOverActions {
            get {
                return ResourceManager.GetString("EtiquetaOverActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mantenimiento de la Página.
        /// </summary>
        public static string EtiquetaPageMaintenance {
            get {
                return ResourceManager.GetString("EtiquetaPageMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Personal.
        /// </summary>
        public static string EtiquetaPersonal {
            get {
                return ResourceManager.GetString("EtiquetaPersonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Posición.
        /// </summary>
        public static string EtiquetaPosition {
            get {
                return ResourceManager.GetString("EtiquetaPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Potencial del incidente.
        /// </summary>
        public static string EtiquetaPotencialIncidente {
            get {
                return ResourceManager.GetString("EtiquetaPotencialIncidente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prioridad.
        /// </summary>
        public static string EtiquetaPrioridad {
            get {
                return ResourceManager.GetString("EtiquetaPrioridad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proyecto.
        /// </summary>
        public static string EtiquetaProject {
            get {
                return ResourceManager.GetString("EtiquetaProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proyecto.
        /// </summary>
        public static string EtiquetaProyecto {
            get {
                return ResourceManager.GetString("EtiquetaProyecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Criado en.
        /// </summary>
        public static string EtiquetaRaisedOn {
            get {
                return ResourceManager.GetString("EtiquetaRaisedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de recurso:.
        /// </summary>
        public static string EtiquetaRecord {
            get {
                return ResourceManager.GetString("EtiquetaRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recursos.
        /// </summary>
        public static string EtiquetaRecordMenu {
            get {
                return ResourceManager.GetString("EtiquetaRecordMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recurso #.
        /// </summary>
        public static string EtiquetaRecordN {
            get {
                return ResourceManager.GetString("EtiquetaRecordN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repita esta acción cada.
        /// </summary>
        public static string EtiquetaRepeatAction {
            get {
                return ResourceManager.GetString("EtiquetaRepeatAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reportes.
        /// </summary>
        public static string EtiquetaReporting {
            get {
                return ResourceManager.GetString("EtiquetaReporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Requiere Informe Final?.
        /// </summary>
        public static string EtiquetaRequiereInformeFinal {
            get {
                return ResourceManager.GetString("EtiquetaRequiereInformeFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Requiere cheque.
        /// </summary>
        public static string EtiquetaRequires {
            get {
                return ResourceManager.GetString("EtiquetaRequires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Requiriendo revision solamente.
        /// </summary>
        public static string EtiquetaRequiring {
            get {
                return ResourceManager.GetString("EtiquetaRequiring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Responsable.
        /// </summary>
        public static string EtiquetaResponsable {
            get {
                return ResourceManager.GetString("EtiquetaResponsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calificación de riesgo:.
        /// </summary>
        public static string EtiquetaRisk {
            get {
                return ResourceManager.GetString("EtiquetaRisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Siglas.
        /// </summary>
        public static string EtiquetaSiglas {
            get {
                return ResourceManager.GetString("EtiquetaSiglas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Anexo.
        /// </summary>
        public static string EtiquetaTipoApendice {
            get {
                return ResourceManager.GetString("EtiquetaTipoApendice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Registro.
        /// </summary>
        public static string EtiquetaTipoRecord {
            get {
                return ResourceManager.GetString("EtiquetaTipoRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SEGUIMIENTO DE ACCIONES.
        /// </summary>
        public static string EtiquetaTitulo {
            get {
                return ResourceManager.GetString("EtiquetaTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ACCIÓN ANULADA POR GERENCIA.
        /// </summary>
        public static string EtiquetaTituloAccionAnuladoGerencia {
            get {
                return ResourceManager.GetString("EtiquetaTituloAccionAnuladoGerencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ACCIÓN CERRADA POR GERENCIA.
        /// </summary>
        public static string EtiquetaTituloAccionCerradoGerencia {
            get {
                return ResourceManager.GetString("EtiquetaTituloAccionCerradoGerencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ACCIÓN REABRIR POR GERENCIA.
        /// </summary>
        public static string EtiquetaTituloAccionReabrirGerencia {
            get {
                return ResourceManager.GetString("EtiquetaTituloAccionReabrirGerencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Cuáles son los detalles del incidente?.
        /// </summary>
        public static string EtiquetaTituloCuerpoTabGeneral {
            get {
                return ResourceManager.GetString("EtiquetaTituloCuerpoTabGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminación de Registro.
        /// </summary>
        public static string EtiquetaTituloEliminar {
            get {
                return ResourceManager.GetString("EtiquetaTituloEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formulario Consulta Registro.
        /// </summary>
        public static string EtiquetaTituloFormularioConsultaRegistro {
            get {
                return ResourceManager.GetString("EtiquetaTituloFormularioConsultaRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formulario Anexo.
        /// </summary>
        public static string EtiquetaTituloFormularioRecordAnexoAccion {
            get {
                return ResourceManager.GetString("EtiquetaTituloFormularioRecordAnexoAccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver Acción.
        /// </summary>
        public static string EtiquetaTituloFormularioVerAccion {
            get {
                return ResourceManager.GetString("EtiquetaTituloFormularioVerAccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguimiento de Acción.
        /// </summary>
        public static string EtiquetaTituloFormularioVerSeguimientoAccion {
            get {
                return ResourceManager.GetString("EtiquetaTituloFormularioVerSeguimientoAccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fotografías.
        /// </summary>
        public static string EtiquetaTituloFotografia {
            get {
                return ResourceManager.GetString("EtiquetaTituloFotografia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Título del Incidente.
        /// </summary>
        public static string EtiquetaTituloIncidente {
            get {
                return ResourceManager.GetString("EtiquetaTituloIncidente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ACCIONES.
        /// </summary>
        public static string EtiquetaTituloPrincipal {
            get {
                return ResourceManager.GetString("EtiquetaTituloPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a REVISAR REGISTRO.
        /// </summary>
        public static string EtiquetaTituloRevisionAccion {
            get {
                return ResourceManager.GetString("EtiquetaTituloRevisionAccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rastreo.
        /// </summary>
        public static string EtiquetaTracking {
            get {
                return ResourceManager.GetString("EtiquetaTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formación.
        /// </summary>
        public static string EtiquetaTraining {
            get {
                return ResourceManager.GetString("EtiquetaTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo.
        /// </summary>
        public static string EtiquetaTypeAnexo {
            get {
                return ResourceManager.GetString("EtiquetaTypeAnexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver Acción.
        /// </summary>
        public static string EtiquetaVerAccion {
            get {
                return ResourceManager.GetString("EtiquetaVerAccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vista Previa de Foto.
        /// </summary>
        public static string EtiquetaVistaPreviaFoto {
            get {
                return ResourceManager.GetString("EtiquetaVistaPreviaFoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Criado en.
        /// </summary>
        public static string GridAccionCriadoEn {
            get {
                return ResourceManager.GetString("GridAccionCriadoEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acciones.
        /// </summary>
        public static string GridAcciones {
            get {
                return ResourceManager.GetString("GridAcciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acción No..
        /// </summary>
        public static string GridAccionNumero {
            get {
                return ResourceManager.GetString("GridAccionNumero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acción Planteada por.
        /// </summary>
        public static string GridAccionPlanteadaPor {
            get {
                return ResourceManager.GetString("GridAccionPlanteadaPor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numero Acción.
        /// </summary>
        public static string GridActionNumber {
            get {
                return ResourceManager.GetString("GridActionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alerta.
        /// </summary>
        public static string GridAlerta {
            get {
                return ResourceManager.GetString("GridAlerta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre Apendice.
        /// </summary>
        public static string GridApendiceName {
            get {
                return ResourceManager.GetString("GridApendiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operacion Area.
        /// </summary>
        public static string GridArea {
            get {
                return ResourceManager.GetString("GridArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clasificacióm.
        /// </summary>
        public static string GridClassification {
            get {
                return ResourceManager.GetString("GridClassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrado.
        /// </summary>
        public static string GridClosed {
            get {
                return ResourceManager.GetString("GridClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrado en.
        /// </summary>
        public static string GridClosedOn {
            get {
                return ResourceManager.GetString("GridClosedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comentario.
        /// </summary>
        public static string GridComentario {
            get {
                return ResourceManager.GetString("GridComentario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        public static string GridDate {
            get {
                return ResourceManager.GetString("GridDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string GridDescripcion {
            get {
                return ResourceManager.GetString("GridDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción Corta Acción.
        /// </summary>
        public static string GridDescripcionCorta {
            get {
                return ResourceManager.GetString("GridDescripcionCorta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción Corta Hallazgo.
        /// </summary>
        public static string GridDescripcionCortaHallazgo {
            get {
                return ResourceManager.GetString("GridDescripcionCortaHallazgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string GridDescription {
            get {
                return ResourceManager.GetString("GridDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Download.
        /// </summary>
        public static string GridDownload {
            get {
                return ResourceManager.GetString("GridDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        public static string GridEstado {
            get {
                return ResourceManager.GetString("GridEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Estado.
        /// </summary>
        public static string GridFechaEstado {
            get {
                return ResourceManager.GetString("GridFechaEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de vencimiento.
        /// </summary>
        public static string GridFechaVencimiento {
            get {
                return ResourceManager.GetString("GridFechaVencimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Item.
        /// </summary>
        public static string GridItem {
            get {
                return ResourceManager.GetString("GridItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Link Revisar record.
        /// </summary>
        public static string GridLink {
            get {
                return ResourceManager.GetString("GridLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nro. Acción.
        /// </summary>
        public static string GridNumeroAccion {
            get {
                return ResourceManager.GetString("GridNumeroAccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nro. Registro.
        /// </summary>
        public static string GridNumeroRegistro {
            get {
                return ResourceManager.GetString("GridNumeroRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acciones Pendientes.
        /// </summary>
        public static string GridOutstanding {
            get {
                return ResourceManager.GetString("GridOutstanding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sobre Acciones.
        /// </summary>
        public static string GridOveractions {
            get {
                return ResourceManager.GetString("GridOveractions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de la foto.
        /// </summary>
        public static string GridPhotoName {
            get {
                return ResourceManager.GetString("GridPhotoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Planteada el día.
        /// </summary>
        public static string GridPlanteadaDia {
            get {
                return ResourceManager.GetString("GridPlanteadaDia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acción planteada por.
        /// </summary>
        public static string GridPlanteadaPor {
            get {
                return ResourceManager.GetString("GridPlanteadaPor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Planteado En.
        /// </summary>
        public static string GridPlanteadoEn {
            get {
                return ResourceManager.GetString("GridPlanteadoEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Posición.
        /// </summary>
        public static string GridPosition {
            get {
                return ResourceManager.GetString("GridPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vista Previa de Foto.
        /// </summary>
        public static string GridPreviewPhoto {
            get {
                return ResourceManager.GetString("GridPreviewPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prioridad.
        /// </summary>
        public static string GridPrioridad {
            get {
                return ResourceManager.GetString("GridPrioridad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proyecto.
        /// </summary>
        public static string GridProject {
            get {
                return ResourceManager.GetString("GridProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recurso #.
        /// </summary>
        public static string GridRecord {
            get {
                return ResourceManager.GetString("GridRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de recurso.
        /// </summary>
        public static string GridRecordType {
            get {
                return ResourceManager.GetString("GridRecordType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reportes.
        /// </summary>
        public static string GridReporting {
            get {
                return ResourceManager.GetString("GridReporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Requiere cheque.
        /// </summary>
        public static string GridRequiresCheck {
            get {
                return ResourceManager.GetString("GridRequiresCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Responsable.
        /// </summary>
        public static string GridResponsable {
            get {
                return ResourceManager.GetString("GridResponsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calificación de riesgo.
        /// </summary>
        public static string GridRiskrating {
            get {
                return ResourceManager.GetString("GridRiskrating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anexo.
        /// </summary>
        public static string GridSeguimientoAnexo {
            get {
                return ResourceManager.GetString("GridSeguimientoAnexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario que realizó el cambio de estado.
        /// </summary>
        public static string GridSeguimientoCerradoPor {
            get {
                return ResourceManager.GetString("GridSeguimientoCerradoPor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comentario.
        /// </summary>
        public static string GridSeguimientoComentario {
            get {
                return ResourceManager.GetString("GridSeguimientoComentario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        public static string GridSeguimientoEstado {
            get {
                return ResourceManager.GetString("GridSeguimientoEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Cierre.
        /// </summary>
        public static string GridSeguimientoFechaCierre {
            get {
                return ResourceManager.GetString("GridSeguimientoFechaCierre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Estado.
        /// </summary>
        public static string GridSeguimientoFechaEstado {
            get {
                return ResourceManager.GetString("GridSeguimientoFechaEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Foto.
        /// </summary>
        public static string GridSeguimientoFoto {
            get {
                return ResourceManager.GetString("GridSeguimientoFoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        public static string GridState {
            get {
                return ResourceManager.GetString("GridState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Estado.
        /// </summary>
        public static string GridStateDate {
            get {
                return ResourceManager.GetString("GridStateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Registro.
        /// </summary>
        public static string GridTipoRegistro {
            get {
                return ResourceManager.GetString("GridTipoRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo.
        /// </summary>
        public static string GridTypeAnexo {
            get {
                return ResourceManager.GetString("GridTypeAnexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vencimiento.
        /// </summary>
        public static string GridVencimiento {
            get {
                return ResourceManager.GetString("GridVencimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe un archivo válido para descarga..
        /// </summary>
        public static string MensajeArchivoValido {
            get {
                return ResourceManager.GetString("MensajeArchivoValido", resourceCulture);
            }
        }
    }
}
