//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pe.ElectroPeru.SGI.Presentacion.Recursos.Mantenimiento.Responsable {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResponsableResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResponsableResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pe.ElectroPeru.SGI.Presentacion.Recursos.Mantenimiento.Responsable.ResponsableRes" +
                            "ource", typeof(ResponsableResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar Colaborador.
        /// </summary>
        public static string BotonAgregarResponsable {
            get {
                return ResourceManager.GetString("BotonAgregarResponsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido Materno.
        /// </summary>
        public static string EtiquetaApellidoMaterno {
            get {
                return ResourceManager.GetString("EtiquetaApellidoMaterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido Paterno.
        /// </summary>
        public static string EtiquetaApellidoPaterno {
            get {
                return ResourceManager.GetString("EtiquetaApellidoPaterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargo.
        /// </summary>
        public static string EtiquetaCargo {
            get {
                return ResourceManager.GetString("EtiquetaCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo Electrónico.
        /// </summary>
        public static string EtiquetaCorreoElectronico {
            get {
                return ResourceManager.GetString("EtiquetaCorreoElectronico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        public static string EtiquetaEditarResponsable {
            get {
                return ResourceManager.GetString("EtiquetaEditarResponsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Género.
        /// </summary>
        public static string EtiquetaGenero {
            get {
                return ResourceManager.GetString("EtiquetaGenero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista.
        /// </summary>
        public static string EtiquetaLista {
            get {
                return ResourceManager.GetString("EtiquetaLista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombres.
        /// </summary>
        public static string EtiquetaNombres {
            get {
                return ResourceManager.GetString("EtiquetaNombres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nº Documento.
        /// </summary>
        public static string EtiquetaNroDocumento {
            get {
                return ResourceManager.GetString("EtiquetaNroDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Responsable.
        /// </summary>
        public static string EtiquetaResponsable {
            get {
                return ResourceManager.GetString("EtiquetaResponsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo Documento.
        /// </summary>
        public static string EtiquetaTipoDocumento {
            get {
                return ResourceManager.GetString("EtiquetaTipoDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mantenimiento de Responsable.
        /// </summary>
        public static string EtiquetaTituloPrincipal {
            get {
                return ResourceManager.GetString("EtiquetaTituloPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido Materno.
        /// </summary>
        public static string GridApellidoMaterno {
            get {
                return ResourceManager.GetString("GridApellidoMaterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido Paterno.
        /// </summary>
        public static string GridApellidoPaterno {
            get {
                return ResourceManager.GetString("GridApellidoPaterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargo.
        /// </summary>
        public static string GridCargo {
            get {
                return ResourceManager.GetString("GridCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo Electrónico.
        /// </summary>
        public static string GridCorreoElectronico {
            get {
                return ResourceManager.GetString("GridCorreoElectronico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        public static string GridEstadoRegistroDescripcion {
            get {
                return ResourceManager.GetString("GridEstadoRegistroDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Género.
        /// </summary>
        public static string GridGenero {
            get {
                return ResourceManager.GetString("GridGenero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombres.
        /// </summary>
        public static string GridNombres {
            get {
                return ResourceManager.GetString("GridNombres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nº Doc..
        /// </summary>
        public static string GridNumeroDocumento {
            get {
                return ResourceManager.GetString("GridNumeroDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo Doc..
        /// </summary>
        public static string GridTipoDocumento {
            get {
                return ResourceManager.GetString("GridTipoDocumento", resourceCulture);
            }
        }
    }
}
